name = "P21"
version = "0.1.0"
defaultTargets = ["P21"]

[leanOptions]
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0-rc1"

[[lean_lib]]
name = "P21"
