import P21

#print axioms P21.NumericalSemigroup.apery_le
#print axioms P21.NumericalSemigroup.apery_finite
#print axioms P21.NumericalSemigroup.zero_mem_apery
#print axioms P21.NumericalSemigroup.W_mem_apery
#print axioms P21.NumericalSemigroup.pf_add_m_mem_apery
#print axioms P21.NumericalSemigroup.apery_lower
#print axioms P21.NumericalSemigroup.pf_iff_maximal_apery
#print axioms P21.NumericalSemigroup.A0
#print axioms P21.NumericalSemigroup.A1
#print axioms P21.NumericalSemigroup.iota
#print axioms P21.NumericalSemigroup.complement_mem_apery
#print axioms P21.NumericalSemigroup.exact_two_layers
#print axioms P21.NumericalSemigroup.a0_lower
#print axioms P21.NumericalSemigroup.a1_upper
#print axioms P21.NumericalSemigroup.iota_involutive
#print axioms P21.NumericalSemigroup.iota_order_reverse
#print axioms P21.NumericalSemigroup.iota_mem_a1
#print axioms P21.NumericalSemigroup.pf_add_m_mem_a1
#print axioms P21.NumericalSemigroup.complement_of_q_mem_apery
#print axioms P21.NumericalSemigroup.maximal_a1_iff
#print axioms P21.NumericalSemigroup.minimal_iff_iota_maximal
#print axioms P21.NumericalSemigroup.minimal_a1_iff
#print axioms P21.NumericalSemigroup.maximal_a1_set
#print axioms P21.NumericalSemigroup.minimal_a1_set
#print axioms P21.NumericalSemigroup.minimal_a1_card
#print axioms P21.Generators.all
#print axioms P21.Generators.Gamma
#print axioms P21.Generators.H
#print axioms P21.Generators.ActualFactorization4
#print axioms P21.Generators.ActualFactorization3
#print axioms P21.Generators.Minimal
#print axioms P21.Generators.TailMinimal
#print axioms P21.Generators.OffDirection
#print axioms P21.Generators.D
#print axioms P21.Generators.SH
#print axioms P21.Generators.tailGcd
#print axioms P21.Generators.value_cons
#print axioms P21.Generators.h_subset_gamma
#print axioms P21.Generators.m_mem
#print axioms P21.Generators.n_mem
#print axioms P21.Generators.tail_minimal
#print axioms P21.Generators.Setting.semigroup
#print axioms P21.Generators.minimal_injective
#print axioms P21.Generators.minimal_four_distinct
#print axioms P21.P21MainStatement
#print axioms P21.Generators.Setting.apery_m_coordinate_zero
#print axioms P21.Generators.Setting.apery_in_tail
#print axioms P21.Generators.Setting.a0_tail_iff
#print axioms P21.Generators.Setting.key_return_apery
#print axioms P21.Generators.Setting.return_coordinate_zero
#print axioms P21.Generators.Setting.key_support_zero
#print axioms P21.Generators.Setting.support_nonempty
#print axioms P21.Generators.Setting.key_support_inclusion
#print axioms P21.Generators.Setting.supported_rectangle
#print axioms P21.value
#print axioms P21.generated
#print axioms P21.actual_iff_mem
#print axioms P21.generator_mem
#print axioms P21.generated_nonneg
#print axioms P21.replaceWithinActualFactorization
#print axioms P21.removeOne
#print axioms P21.NumericalSemigroup.Gap
#print axioms P21.NumericalSemigroup.IsFrobenius
#print axioms P21.NumericalSemigroup.PF
#print axioms P21.NumericalSemigroup.type
#print axioms P21.NumericalSemigroup.Apery
#print axioms P21.NumericalSemigroup.Le
#print axioms P21.NumericalSemigroup.Canonical
#print axioms P21.NumericalSemigroup.Q
#print axioms P21.NumericalSemigroup.Maximal
#print axioms P21.NumericalSemigroup.Minimal
#print axioms P21.NumericalSemigroup.le_refl
#print axioms P21.NumericalSemigroup.le_trans
#print axioms P21.NumericalSemigroup.le_antisymm
#print axioms P21.NumericalSemigroup.exists_frobenius
#print axioms P21.NumericalSemigroup.frobenius_mem_pf
#print axioms P21.NumericalSemigroup.mem_of_gt_frobenius
#print axioms P21.NumericalSemigroup.pf_finite
#print axioms P21.NumericalSemigroup.q_lt_frobenius
#print axioms P21.NumericalSemigroup.type_eq_q_card_add_one
#print axioms P21.NumericalSemigroup.translated_gaps_finite
#print axioms P21.NumericalSemigroup.gap_below_pf
#print axioms P21.NumericalSemigroup.canonical_all_nonnegative_gaps
#print axioms P21.Generators.offDirection_iff_pair
#print axioms P21.Generators.Setting.key_pair_return
#print axioms P21.Generators.Setting.RowFacts
#print axioms P21.Generators.Setting.all_q_row_facts
#print axioms P21.Generators.Setting.select_four_rows
#print axioms P21.Generators.Setting.tail_minimal_and_cofinite
#print axioms P21.W
#print axioms P21.complement
#print axioms P21.cofinite_iff_finite_nonnegative_gaps
#print axioms P21.NumericalSemigroup.all_pf_finite
#print axioms P21.NumericalSemigroup.q_finite
#print axioms P21.NumericalSemigroup.a0_lower_in_semigroup
#print axioms P21.NumericalSemigroup.minimal_a1_card_eq_type_sub_one
#print axioms P21.divisor_of_generated
#print axioms P21.generated_eq_closure
#print axioms P21.signed_mem_group
#print axioms P21.Generators.Setting.tail_signed_m
#print axioms P21.Generators.Setting.m_mem_tail_group
#print axioms P21.Generators.Setting.common_divisor_dvd_one
#print axioms P21.Generators.Setting.tail_common_divisor_dvd_one
#print axioms P21.Generators.Setting.tail_gcd_eq_one
#print axioms P21.Generators.Setting.natural_closure_to_tail
#print axioms P21.Generators.Setting.tail_cofinite
#print axioms P21.Generators.Setting.tailSemigroup
