import P21.Symmetric.BranchI
import P21.Symmetric.BranchIActual
import P21.Symmetric.BranchII
import P21.Symmetric.BranchIIActual
import P21.Symmetric.Closure
import P21.Symmetric.CrossLayer
import P21.Symmetric.GlueNormalForm
import P21.Symmetric.Raw4
import P21.Symmetric.Raw4Consequences
import P21.Symmetric.RawRows
import P21.Symmetric.Reduction
import P21.Symmetric.StableCore
import P21.Symmetric.TwoGenerator
import P21.Symmetric.TwoGeneratorIdeal
import P21.Symmetric.TypeBridge
import P21.External.SymmetricThreeGenerator

#check P21.Symmetric.BranchIData
#check P21.Symmetric.BranchIData.w
#check P21.Symmetric.BranchIData.L
#check P21.Symmetric.BranchIData.ρ
#check P21.Symmetric.BranchIData.c
#check P21.Symmetric.BranchIData.j
#check P21.Symmetric.BranchIData.τ
#check P21.Symmetric.BranchIData.Ux
#check P21.Symmetric.BranchIData.Uy
#check P21.Symmetric.BranchIData.Zx
#check P21.Symmetric.BranchIData.Zy
#check P21.Symmetric.BranchIData.Stable
#check P21.Symmetric.BranchIData.FourHits
#check P21.Symmetric.BranchIData.j_eq_emod
#check P21.Symmetric.BranchIData.j_bounds
#check P21.Symmetric.BranchIData.step
#check P21.Symmetric.BranchIData.return_previous
#check P21.Symmetric.BranchIData.return_next
#check P21.Symmetric.BranchIData.c_zero
#check P21.Symmetric.BranchIData.c_one
#check P21.Symmetric.BranchIData.first_return
#check P21.Symmetric.BranchIData.later_return_lower
#check P21.Symmetric.BranchIData.not_both_late
#check P21.Symmetric.BranchIData.ux_carry
#check P21.Symmetric.BranchIData.x_only
#check P21.Symmetric.BranchIData.swap
#check P21.Symmetric.BranchIData.stable_swap
#check P21.Symmetric.BranchIData.y_only
#check P21.Symmetric.BranchIData.xy_upper_x
#check P21.Symmetric.BranchIData.xy
#check P21.Symmetric.BranchIData.four_hits_impossible
#check P21.Symmetric.BranchIData.rectangle_translation
#check P21.Symmetric.BranchIData.ux_translation
#check P21.Symmetric.BranchIData.zx_translation
#check P21.Symmetric.BranchIData.uy_translation
#check P21.Symmetric.BranchIData.zy_translation
#check P21.Symmetric.BranchIData.firstReturnExample
#check P21.Symmetric.BranchIData.first_return_exception
#check P21.Symmetric.BranchIData.firstReturnExample_periodic
#check P21.Symmetric.BranchIData.firstReturnExample_stable
#check P21.Symmetric.BranchIRealization
#check P21.Symmetric.BranchIRealization.normal_mem
#check P21.Symmetric.BranchIRealization.represented_mem
#check P21.Symmetric.BranchIRealization.x_eq
#check P21.Symmetric.BranchIRealization.y_eq
#check P21.Symmetric.BranchIRealization.z_eq
#check P21.Symmetric.BranchIRealization.walk_identity
#check P21.Symmetric.BranchIRealization.stable_iff
#check P21.Symmetric.BranchIRealization.stable
#check P21.Symmetric.BranchIRealization.ux_hit
#check P21.Symmetric.BranchIRealization.uy_hit
#check P21.Symmetric.BranchIRealization.zx_hit
#check P21.Symmetric.BranchIRealization.zy_hit
#check P21.Symmetric.BranchIRealization.four_hits
#check P21.Symmetric.BranchIRealization.impossible
#check P21.Symmetric.BranchII.k1_aux_pos
#check P21.Symmetric.BranchII.k1_reduces_to_branchI
#check P21.Symmetric.BranchII.k0_e0_impossible
#check P21.Symmetric.BranchII.k0_theta_coefficients
#check P21.Symmetric.BranchII.div_eq_of_bounds
#check P21.Symmetric.BranchII.carry
#check P21.Symmetric.BranchII.ceiling
#check P21.Symmetric.BranchII.epsilon
#check P21.Symmetric.BranchII.tau
#check P21.Symmetric.BranchII.complement
#check P21.Symmetric.BranchII.complement_add_tau
#check P21.Symmetric.BranchII.carry_of_residue
#check P21.Symmetric.BranchII.ceiling_of_residue
#check P21.Symmetric.BranchII.epsilon_zero_or_one
#check P21.Symmetric.BranchII.epsilon_one_residue
#check P21.Symmetric.BranchII.epsilon_one_predecessor
#check P21.Symmetric.BranchII.crosscore_phase
#check P21.Symmetric.BranchII.shift_gap_has_axis
#check P21.Symmetric.BranchII.crosscore_shift_mem
#check P21.Symmetric.BranchII.layer
#check P21.Symmetric.BranchII.complementLayer
#check P21.Symmetric.BranchII.layer_bounds
#check P21.Symmetric.BranchII.complementLayer_bounds
#check P21.Symmetric.BranchII.stable_coordinate_identity
#check P21.Symmetric.BranchII.complement_coordinate_identity
#check P21.Symmetric.BranchIIActual.row_x
#check P21.Symmetric.BranchIIActual.row_y
#check P21.Symmetric.BranchIIActual.row_px
#check P21.Symmetric.BranchIIActual.row_py
#check P21.Symmetric.BranchIIActual.rho_uv
#check P21.Symmetric.BranchIIActual.rho_primed_uv
#check P21.Symmetric.BranchIIActual.m_lt_w
#check P21.Symmetric.BranchIIActual.actual_fs
#check P21.Symmetric.BranchIIActual.actual_complement_gap
#check P21.Symmetric.BranchIIActual.x_minus_y_mem
#check P21.Symmetric.BranchIIActual.k1_excluded
#check P21.Symmetric.BranchIIActual.k0_excluded
#check P21.Symmetric.Raw4Data.branchII_excluded
#check P21.Symmetric.symmetric_tail_from_glue_data
#check P21.Symmetric.nonnegative_mul_mem
#check P21.Symmetric.cross_layer_drop
#check P21.Symmetric.cross_layer_identity
#check P21.Symmetric.complete_split
#check P21.Symmetric.SymmetricGlueData
#check P21.Symmetric.SymmetricGlueData.d_pos
#check P21.Symmetric.SymmetricGlueData.bezout
#check P21.Symmetric.SymmetricGlueData.normal_form_exists
#check P21.Symmetric.SymmetricGlueData.normal_form_unique
#check P21.Symmetric.SymmetricGlueData.represented
#check P21.Symmetric.SymmetricGlueData.d_mul_mem_tail
#check P21.Symmetric.SymmetricGlueData.w_mem_tail
#check P21.Symmetric.SymmetricGlueData.represented_eq_tail
#check P21.Symmetric.SymmetricGlueData.mem_tail_iff
#check P21.Symmetric.SymmetricGlueData.normal_form_mem_iff
#check P21.Symmetric.SymmetricGlueData.frobenius
#check P21.Symmetric.SymmetricGlueData.symmetry
#check P21.Symmetric.SymmetricGlueData.isGreatest_gap
#check P21.Symmetric.SymmetricGlueData.w_pos
#check P21.Symmetric.SymmetricGlueData.normal_form_existsUnique
#check P21.Symmetric.SymmetricGlueData.tailSemigroup
#check P21.Symmetric.SymmetricGlueData.isFrobenius
#check P21.Symmetric.Raw4Data
#check P21.Symmetric.SymmetricGlueData.intersection_low
#check P21.Symmetric.SymmetricGlueData.intersection_high
#check P21.Symmetric.SymmetricGlueData.raw_min_layers
#check P21.Symmetric.SymmetricGlueData.rawCandidates
#check P21.Symmetric.SymmetricGlueData.raw_min_subset
#check P21.Symmetric.SymmetricGlueData.rawCandidates_ncard_le
#check P21.Symmetric.SymmetricGlueData.raw_min_ncard_le_four
#check P21.Symmetric.SymmetricGlueData.raw_min_zero_subset
#check P21.Symmetric.SymmetricGlueData.raw_min_zero_ncard_le_two
#check P21.Symmetric.SymmetricGlueData.surviving_eq_candidates
#check P21.Symmetric.SymmetricGlueData.four_set_pair_distinct
#check P21.Symmetric.SymmetricGlueData.exists_raw4
#check P21.Symmetric.BranchIRealization.difference_pos
#check P21.Symmetric.Raw4Data.row_x
#check P21.Symmetric.Raw4Data.row_y
#check P21.Symmetric.Raw4Data.row_px
#check P21.Symmetric.Raw4Data.row_py
#check P21.Symmetric.Raw4Data.A_lt
#check P21.Symmetric.Raw4Data.B_lt
#check P21.Symmetric.Raw4Data.Ap_lt
#check P21.Symmetric.Raw4Data.Bp_lt
#check P21.Symmetric.Raw4Data.rho_formula
#check P21.Symmetric.Raw4Data.rhop_formula
#check P21.Symmetric.Raw4Data.rho_y
#check P21.Symmetric.Raw4Data.rhop_y
#check P21.Symmetric.Raw4Data.Ap_lt_A
#check P21.Symmetric.Raw4Data.Bp_lt_B
#check P21.Symmetric.Raw4Data.w_formula
#check P21.Symmetric.Raw4Data.split
#check P21.Symmetric.Raw4Data.branchI_excluded
#check P21.Symmetric.ActualRawRow
#check P21.Symmetric.ActualRawRow.pf
#check P21.Symmetric.ActualRawRow.core
#check P21.Symmetric.ActualRawRow.all_ap
#check P21.Symmetric.ActualRawRow.sub_multiple_gap
#check P21.Symmetric.ActualRawRow.backward_gap
#check P21.Symmetric.ActualRawRow.pf_add_m_mem_tail
#check P21.Symmetric.ActualRawRow.pf_add_tail_generator
#check P21.Symmetric.ActualRawRow.predecessor_not_stable
#check P21.Symmetric.ActualRawRow.positive_hit_required
#check P21.Symmetric.SymmetricGlueData.layer_mem_iff
#check P21.Symmetric.SymmetricGlueData.multiplicity_bounds
#check P21.Symmetric.SymmetricGlueData.multiplicity_coordinate_gap
#check P21.Symmetric.SymmetricGlueData.carry_binary
#check P21.Symmetric.SymmetricGlueData.carry_one_iff
#check P21.Symmetric.SymmetricGlueData.qm_x_coordinate
#check P21.Symmetric.SymmetricGlueData.qm_y_coordinate
#check P21.Symmetric.SymmetricAt
#check P21.Symmetric.stableCore
#check P21.Symmetric.shiftedCore
#check P21.Symmetric.idealMin
#check P21.Symmetric.mem_gamma_iff_tail_add
#check P21.Symmetric.stableCore_subset_tail
#check P21.Symmetric.gap_iff_stableCore
#check P21.Symmetric.stableCore_add_gamma
#check P21.Symmetric.stableCore_isLeast
#check P21.Symmetric.m_not_mem_tail
#check P21.Symmetric.stableCore_zero_not_mem
#check P21.Symmetric.stableCore_mem_gt_m
#check P21.Symmetric.stableCore_min_gt_m
#check P21.Symmetric.stable_shift_pos
#check P21.Symmetric.stable_walk
#check P21.Symmetric.pf_iff_min_stableCore
#check P21.Symmetric.shiftedCore_subset_gamma
#check P21.Symmetric.shiftedCore_isLeast
#check P21.Symmetric.frobenius_eq_sub_core_min
#check P21.Symmetric.symmetricAt_f_not_mem
#check P21.Symmetric.symmetricAt_gap_le
#check P21.Symmetric.TwoGeneratorData
#check P21.Symmetric.TwoGeneratorData.T
#check P21.Symmetric.TwoGeneratorData.mem_T
#check P21.Symmetric.TwoGeneratorData.T_eq_generated
#check P21.Symmetric.TwoGeneratorData.u_pos
#check P21.Symmetric.TwoGeneratorData.v_pos
#check P21.Symmetric.TwoGeneratorData.nonneg
#check P21.Symmetric.TwoGeneratorData.bezout
#check P21.Symmetric.TwoGeneratorData.representation_difference
#check P21.Symmetric.TwoGeneratorData.normal_form_exists
#check P21.Symmetric.TwoGeneratorData.normal_form_unique
#check P21.Symmetric.TwoGeneratorData.normal_form_mem_iff
#check P21.Symmetric.TwoGeneratorData.frobenius
#check P21.Symmetric.TwoGeneratorData.frobenius_symmetry
#check P21.Symmetric.TwoGeneratorData.subcritical_nonneg
#check P21.Symmetric.TwoGeneratorData.interior_gap
#check P21.Symmetric.TwoGeneratorData.subcritical_gap
#check P21.Symmetric.TwoGeneratorData.two_generator_intersection_iff
#check P21.Symmetric.TwoGeneratorData.translate
#check P21.Symmetric.TwoGeneratorData.two_generator_intersection
#check P21.Symmetric.TwoGeneratorData.mem_of_gt_frobenius
#check P21.Symmetric.TwoGeneratorData.semigroup
#check P21.Symmetric.TwoGeneratorData.isFrobenius
#check P21.Symmetric.TwoGeneratorData.normal_form_existsUnique
#check P21.Symmetric.TwoGeneratorData.intersectionIdeal
#check P21.Symmetric.TwoGeneratorData.intersectionIdeal_add
#check P21.Symmetric.TwoGeneratorData.firstThreshold
#check P21.Symmetric.TwoGeneratorData.secondThreshold
#check P21.Symmetric.TwoGeneratorData.firstThreshold_mem
#check P21.Symmetric.TwoGeneratorData.secondThreshold_mem
#check P21.Symmetric.TwoGeneratorData.intersectionIdeal_generators
#check P21.Symmetric.TwoGeneratorData.minimal_mem_pair
#check P21.Symmetric.TwoGeneratorData.minimal_finite
#check P21.Symmetric.TwoGeneratorData.minimal_ncard_le_two
#check P21.Symmetric.TwoGeneratorData.minima_incomparable
#check P21.Symmetric.TwoGeneratorData.two_minima_forces_bounds
#check P21.Symmetric.TwoGeneratorData.minimal_pair_eq
#check P21.Symmetric.TwoGeneratorData.two_minima_iff
#check P21.Symmetric.tailIntersection
#check P21.Symmetric.minimal_bridge
#check P21.Symmetric.distinguished_not_raw_apery
#check P21.Symmetric.idealMin_shift
#check P21.Symmetric.min_shiftedCore_iff_pf
#check P21.Symmetric.tailIntersection_iff_shiftedCore
#check P21.Symmetric.exact_bridge
#check P21.Symmetric.min_shiftedCore_set
#check P21.Symmetric.type_bridge
#check P21.Symmetric.SymmetricTail
#check P21.Symmetric.SymmetricThreeGeneratorGluingStatement
#check P21.Symmetric.glue_data_symmetric_tail
#print P21.Symmetric.SymmetricGlueData
#print P21.Symmetric.SymmetricTail
#print P21.Symmetric.SymmetricThreeGeneratorGluingStatement
#check P21.Symmetric.symmetric_tail_from_glue_data
