import P21
set_option pp.universes false

#check P21.NumericalSemigroup.apery_le
#check P21.NumericalSemigroup.apery_finite
#check P21.NumericalSemigroup.zero_mem_apery
#check P21.NumericalSemigroup.W_mem_apery
#check P21.NumericalSemigroup.pf_add_m_mem_apery
#check P21.NumericalSemigroup.apery_lower
#check P21.NumericalSemigroup.pf_iff_maximal_apery
#check P21.NumericalSemigroup.A0
#check P21.NumericalSemigroup.A1
#check P21.NumericalSemigroup.iota
#check P21.NumericalSemigroup.complement_mem_apery
#check P21.NumericalSemigroup.exact_two_layers
#check P21.NumericalSemigroup.a0_lower
#check P21.NumericalSemigroup.a1_upper
#check P21.NumericalSemigroup.iota_involutive
#check P21.NumericalSemigroup.iota_order_reverse
#check P21.NumericalSemigroup.iota_mem_a1
#check P21.NumericalSemigroup.pf_add_m_mem_a1
#check P21.NumericalSemigroup.complement_of_q_mem_apery
#check P21.NumericalSemigroup.maximal_a1_iff
#check P21.NumericalSemigroup.minimal_iff_iota_maximal
#check P21.NumericalSemigroup.minimal_a1_iff
#check P21.NumericalSemigroup.maximal_a1_set
#check P21.NumericalSemigroup.minimal_a1_set
#check P21.NumericalSemigroup.minimal_a1_card
#check P21.Generators
#check P21.Generators.all
#check P21.Generators.Gamma
#check P21.Generators.H
#check P21.Generators.ActualFactorization4
#check P21.Generators.ActualFactorization3
#check P21.Generators.Minimal
#check P21.Generators.TailMinimal
#check P21.Generators.OffDirection
#check P21.Generators.D
#check P21.Generators.SH
#check P21.Generators.tailGcd
#check P21.Generators.value_cons
#check P21.Generators.h_subset_gamma
#check P21.Generators.m_mem
#check P21.Generators.n_mem
#check P21.Generators.tail_minimal
#check P21.Generators.Setting
#check P21.Generators.Setting.semigroup
#check P21.Generators.minimal_injective
#check P21.Generators.minimal_four_distinct
#check P21.P21MainStatement
#check P21.Generators.Setting.apery_m_coordinate_zero
#check P21.Generators.Setting.apery_in_tail
#check P21.Generators.Setting.a0_tail_iff
#check P21.Generators.Setting.key_return_apery
#check P21.Generators.Setting.return_coordinate_zero
#check P21.Generators.Setting.key_support_zero
#check P21.Generators.Setting.support_nonempty
#check P21.Generators.Setting.key_support_inclusion
#check P21.Generators.Setting.supported_rectangle
#check P21.value
#check P21.ActualFactorization
#check P21.generated
#check P21.actual_iff_mem
#check P21.generator_mem
#check P21.generated_nonneg
#check P21.replaceWithinActualFactorization
#check P21.removeOne
#check P21.SignedRepresentation
#check P21.SignedRelation3
#check P21.NumericalSemigroup
#check P21.NumericalSemigroup.Gap
#check P21.NumericalSemigroup.IsFrobenius
#check P21.NumericalSemigroup.PF
#check P21.NumericalSemigroup.type
#check P21.NumericalSemigroup.Apery
#check P21.NumericalSemigroup.Le
#check P21.NumericalSemigroup.Canonical
#check P21.NumericalSemigroup.Q
#check P21.NumericalSemigroup.Maximal
#check P21.NumericalSemigroup.Minimal
#check P21.NumericalSemigroup.le_refl
#check P21.NumericalSemigroup.le_trans
#check P21.NumericalSemigroup.le_antisymm
#check P21.NumericalSemigroup.exists_frobenius
#check P21.NumericalSemigroup.frobenius_mem_pf
#check P21.NumericalSemigroup.mem_of_gt_frobenius
#check P21.NumericalSemigroup.pf_finite
#check P21.NumericalSemigroup.q_lt_frobenius
#check P21.NumericalSemigroup.type_eq_q_card_add_one
#check P21.NumericalSemigroup.translated_gaps_finite
#check P21.NumericalSemigroup.gap_below_pf
#check P21.NumericalSemigroup.canonical_all_nonnegative_gaps
#check P21.Generators.offDirection_iff_pair
#check P21.Generators.Setting.key_pair_return
#check P21.Generators.Setting.RowFacts
#check P21.Generators.Setting.all_q_row_facts
#check P21.Generators.Setting.select_four_rows
#check P21.Generators.Setting.tail_minimal_and_cofinite
#check P21.W
#check P21.complement
#check P21.cofinite_iff_finite_nonnegative_gaps
#check P21.NumericalSemigroup.all_pf_finite
#check P21.NumericalSemigroup.q_finite
#check P21.NumericalSemigroup.a0_lower_in_semigroup
#check P21.NumericalSemigroup.minimal_a1_card_eq_type_sub_one
#check P21.divisor_of_generated
#check P21.generated_eq_closure
#check P21.signed_mem_group
#check P21.Generators.Setting.tail_signed_m
#check P21.Generators.Setting.m_mem_tail_group
#check P21.Generators.Setting.common_divisor_dvd_one
#check P21.Generators.Setting.tail_common_divisor_dvd_one
#check P21.Generators.Setting.tail_gcd_eq_one
#check P21.Generators.Setting.natural_closure_to_tail
#check P21.Generators.Setting.tail_cofinite
#check P21.Generators.Setting.tailSemigroup
#print P21.P21MainStatement
#print P21.Generators.Setting
#print P21.Generators.Minimal
#print P21.NumericalSemigroup.PF
#print P21.NumericalSemigroup.IsFrobenius
