import P21.Nonsymmetric.ActualClassification

#check P21.Nonsymmetric.actual_labels_compatible
#check P21.Nonsymmetric.actual_labels_terminal
#print axioms P21.Nonsymmetric.relabel
#print axioms P21.Nonsymmetric.value_perm
#print axioms P21.Nonsymmetric.value_relabel
#print axioms P21.Nonsymmetric.relabel_H
#print axioms P21.Nonsymmetric.value_relabel_all
#print axioms P21.Nonsymmetric.relabel_Gamma
#print axioms P21.Nonsymmetric.relabelSetting
#print axioms P21.Nonsymmetric.relabel_semigroup
#print axioms P21.Nonsymmetric.relabel_SH
#print axioms P21.Nonsymmetric.relabel_TailPF
#print axioms P21.Nonsymmetric.relabel_singleton_iff
#print axioms P21.Nonsymmetric.relabelCritical
#print axioms P21.Nonsymmetric.cyclePerm
#print axioms P21.Nonsymmetric.rotatePerm
#print axioms P21.Nonsymmetric.rotatePerm_zero
#print axioms P21.Nonsymmetric.rotatePerm_one
#print axioms P21.Nonsymmetric.rotatePerm_two
#print axioms P21.Nonsymmetric.rotateHerzog
#print axioms P21.Nonsymmetric.rotateHerzog_fA
#print axioms P21.Nonsymmetric.rotateHerzog_fB
#print axioms P21.Nonsymmetric.rotateFullHerzog
#print axioms P21.Nonsymmetric.reversePerm
#print axioms P21.Nonsymmetric.reverseHerzog
#print axioms P21.Nonsymmetric.reverseHerzog_fA
#print axioms P21.Nonsymmetric.reverseHerzog_fB
#print axioms P21.Nonsymmetric.reverseFullHerzog
#print axioms P21.Nonsymmetric.relabel_complement
#print axioms P21.Nonsymmetric.relabel_W
#print axioms P21.Nonsymmetric.relabel_Q
#print axioms P21.Nonsymmetric.rotate_A_arm_iff
#print axioms P21.Nonsymmetric.rotate_B_arm_iff
#print axioms P21.Nonsymmetric.reverse_A_arm_iff
#print axioms P21.Nonsymmetric.reverse_B_arm_iff
#print axioms P21.Nonsymmetric.relabelFactorization
#print axioms P21.Nonsymmetric.unlabelFactorization
#print axioms P21.Nonsymmetric.relabelActualRow
#print axioms P21.Nonsymmetric.relabelFourRows
#print axioms P21.Nonsymmetric.relabel_D
#print axioms P21.Nonsymmetric.relabel_id
#print axioms P21.Nonsymmetric.relabel_comp
#print axioms P21.Nonsymmetric.rotate_isArmA
#print axioms P21.Nonsymmetric.rotate_isArmB
#print axioms P21.Nonsymmetric.reverse_isArmA
#print axioms P21.Nonsymmetric.reverse_isArmB
#print axioms P21.Nonsymmetric.reversePerm_self
#print axioms P21.Nonsymmetric.reversePerm_next
#print axioms P21.Nonsymmetric.reversePerm_prev
#print axioms P21.Nonsymmetric.armA_not_singleton
#print axioms P21.Nonsymmetric.armB_not_singleton
#print axioms P21.Nonsymmetric.actual_A_box
#print axioms P21.Nonsymmetric.actual_B_box
#print axioms P21.Nonsymmetric.actual_matched_data
#print axioms P21.Nonsymmetric.actual_AA_exclusions
#print axioms P21.Nonsymmetric.actual_matched_exclusions
#print axioms P21.Nonsymmetric.actual_AA_cyclic
#print axioms P21.Nonsymmetric.actual_BB_cyclic
#print axioms P21.Nonsymmetric.no_two_singletons_of_three_directions
#print axioms P21.Nonsymmetric.actual_AA_no_two_singletons
#print axioms P21.Nonsymmetric.actual_BB_no_two_singletons
#print axioms P21.Nonsymmetric.selected_four_Q_card
#print axioms P21.Nonsymmetric.actual_three_A_excluded
#print axioms P21.Nonsymmetric.actual_three_B_excluded
#print axioms P21.Nonsymmetric.actual_labels_compatible
#print axioms P21.Nonsymmetric.actual_labels_terminal
