import P21.Nonsymmetric.ActualClassification
import P21.Nonsymmetric.ActualLabels
import P21.Nonsymmetric.ActualMixed
import P21.Nonsymmetric.Arms
import P21.Nonsymmetric.ColorCap.ActualMinimum
import P21.Nonsymmetric.ColorCap.BoxInput
import P21.Nonsymmetric.ColorCap.BoxPaths
import P21.Nonsymmetric.ColorCap.CompanionBounds
import P21.Nonsymmetric.ColorCap.DPEOneColor
import P21.Nonsymmetric.ColorCap.PositiveMinors
import P21.Nonsymmetric.ColorCap.PrefixArithmetic
import P21.Nonsymmetric.ColorCap.RelativeLattice
import P21.Nonsymmetric.ColorCap.Residuals
import P21.Nonsymmetric.ColorCap.ThreeArms
import P21.Nonsymmetric.ColorCap.WhiteCertificates
import P21.Nonsymmetric.ComplementGeometry
import P21.Nonsymmetric.Corners
import P21.Nonsymmetric.CriticalBox
import P21.Nonsymmetric.Extraction
import P21.Nonsymmetric.FourRowCombinatorics
import P21.Nonsymmetric.Herzog.PseudoFrobenius
import P21.Nonsymmetric.HerzogClassification
import P21.Nonsymmetric.HerzogCoordinates
import P21.Nonsymmetric.HerzogData
import P21.Nonsymmetric.Kernel
import P21.Nonsymmetric.MatchedPair
import P21.Nonsymmetric.MixedColor
import P21.Nonsymmetric.PrimitiveGenerators
import P21.Nonsymmetric.Relabel
import P21.Nonsymmetric.ReturnLevels
import P21.Nonsymmetric.RowAtlas
import P21.Nonsymmetric.Rows
import P21.Nonsymmetric.SameColor
import P21.Nonsymmetric.Saturation
import P21.Nonsymmetric.SelectedExtraction
import P21.Nonsymmetric.Singletons

-- Deliberately audit generated helpers as well as public roots.
set_option linter.auxLemma false
#print axioms P21.Nonsymmetric.ActualLabeling
#print axioms P21.Nonsymmetric.ActualLabeling._sizeOf_1
#print axioms P21.Nonsymmetric.ActualLabeling._sizeOf_inst
#print axioms P21.Nonsymmetric.ActualLabeling.casesOn
#print axioms P21.Nonsymmetric.ActualLabeling.ctorIdx
#print axioms P21.Nonsymmetric.ActualLabeling.label
#print axioms P21.Nonsymmetric.ActualLabeling.label_injective
#print axioms P21.Nonsymmetric.ActualLabeling.labels
#print axioms P21.Nonsymmetric.ActualLabeling.labels.eq_1
#print axioms P21.Nonsymmetric.ActualLabeling.labels_card
#print axioms P21.Nonsymmetric.ActualLabeling.mem_labels
#print axioms P21.Nonsymmetric.ActualLabeling.mk
#print axioms P21.Nonsymmetric.ActualLabeling.mk._flat_ctor
#print axioms P21.Nonsymmetric.ActualLabeling.mk.congr_simp
#print axioms P21.Nonsymmetric.ActualLabeling.mk.inj
#print axioms P21.Nonsymmetric.ActualLabeling.mk.injEq
#print axioms P21.Nonsymmetric.ActualLabeling.mk.noConfusion
#print axioms P21.Nonsymmetric.ActualLabeling.mk.sizeOf_spec
#print axioms P21.Nonsymmetric.ActualLabeling.noConfusion
#print axioms P21.Nonsymmetric.ActualLabeling.noConfusionType
#print axioms P21.Nonsymmetric.ActualLabeling.pick
#print axioms P21.Nonsymmetric.ActualLabeling.pick_label
#print axioms P21.Nonsymmetric.ActualLabeling.pick_permutation
#print axioms P21.Nonsymmetric.ActualLabeling.pick_realizes
#print axioms P21.Nonsymmetric.ActualLabeling.realizes
#print axioms P21.Nonsymmetric.ActualLabeling.rec
#print axioms P21.Nonsymmetric.ActualLabeling.recOn
#print axioms P21.Nonsymmetric.ActualLabeling.reverse
#print axioms P21.Nonsymmetric.ActualLabeling.reverse._proof_1
#print axioms P21.Nonsymmetric.ActualLabeling.reverse.eq_1
#print axioms P21.Nonsymmetric.ActualLabeling.reverse_image_labels
#print axioms P21.Nonsymmetric.ActualLabeling.reverse_labels
#print axioms P21.Nonsymmetric.ActualLabeling.rotate
#print axioms P21.Nonsymmetric.ActualLabeling.rotate._proof_1
#print axioms P21.Nonsymmetric.ActualLabeling.rotate._proof_2
#print axioms P21.Nonsymmetric.ActualLabeling.rotate.eq_1
#print axioms P21.Nonsymmetric.ActualLabeling.rotate_labels
#print axioms P21.Nonsymmetric.ActualQRow
#print axioms P21.Nonsymmetric.ActualQRow._sizeOf_1
#print axioms P21.Nonsymmetric.ActualQRow._sizeOf_inst
#print axioms P21.Nonsymmetric.ActualQRow.casesOn
#print axioms P21.Nonsymmetric.ActualQRow.ctorIdx
#print axioms P21.Nonsymmetric.ActualQRow.mem
#print axioms P21.Nonsymmetric.ActualQRow.mk
#print axioms P21.Nonsymmetric.ActualQRow.mk._flat_ctor
#print axioms P21.Nonsymmetric.ActualQRow.mk.inj
#print axioms P21.Nonsymmetric.ActualQRow.mk.injEq
#print axioms P21.Nonsymmetric.ActualQRow.mk.noConfusion
#print axioms P21.Nonsymmetric.ActualQRow.mk.sizeOf_spec
#print axioms P21.Nonsymmetric.ActualQRow.noConfusion
#print axioms P21.Nonsymmetric.ActualQRow.noConfusionType
#print axioms P21.Nonsymmetric.ActualQRow.q
#print axioms P21.Nonsymmetric.ActualQRow.rec
#print axioms P21.Nonsymmetric.ActualQRow.recOn
#print axioms P21.Nonsymmetric.ChainInput
#print axioms P21.Nonsymmetric.ChainInput.Ai_missing
#print axioms P21.Nonsymmetric.ChainInput.Ak_missing
#print axioms P21.Nonsymmetric.ChainInput.Bi_missing
#print axioms P21.Nonsymmetric.ChainInput.Bj_missing
#print axioms P21.Nonsymmetric.ChainInput.P_exact
#print axioms P21.Nonsymmetric.ChainInput.P_exact._proof_1_3
#print axioms P21.Nonsymmetric.ChainInput._sizeOf_1
#print axioms P21.Nonsymmetric.ChainInput._sizeOf_inst
#print axioms P21.Nonsymmetric.ChainInput.actual
#print axioms P21.Nonsymmetric.ChainInput.all_slacks_positive
#print axioms P21.Nonsymmetric.ChainInput.all_slacks_positive._proof_1_5
#print axioms P21.Nonsymmetric.ChainInput.alpha
#print axioms P21.Nonsymmetric.ChainInput.alpha.eq_1
#print axioms P21.Nonsymmetric.ChainInput.beta
#print axioms P21.Nonsymmetric.ChainInput.beta.eq_1
#print axioms P21.Nonsymmetric.ChainInput.boxW
#print axioms P21.Nonsymmetric.ChainInput.cAi
#print axioms P21.Nonsymmetric.ChainInput.cAk
#print axioms P21.Nonsymmetric.ChainInput.cBi
#print axioms P21.Nonsymmetric.ChainInput.cBj
#print axioms P21.Nonsymmetric.ChainInput.casesOn
#print axioms P21.Nonsymmetric.ChainInput.ctorIdx
#print axioms P21.Nonsymmetric.ChainInput.delta
#print axioms P21.Nonsymmetric.ChainInput.delta._proof_1
#print axioms P21.Nonsymmetric.ChainInput.delta.eq_1
#print axioms P21.Nonsymmetric.ChainInput.distinct
#print axioms P21.Nonsymmetric.ChainInput.gapJ
#print axioms P21.Nonsymmetric.ChainInput.gapJ.eq_1
#print axioms P21.Nonsymmetric.ChainInput.lambda
#print axioms P21.Nonsymmetric.ChainInput.lambda_range
#print axioms P21.Nonsymmetric.ChainInput.mk
#print axioms P21.Nonsymmetric.ChainInput.mk._flat_ctor
#print axioms P21.Nonsymmetric.ChainInput.mk.inj
#print axioms P21.Nonsymmetric.ChainInput.mk.injEq
#print axioms P21.Nonsymmetric.ChainInput.mk.noConfusion
#print axioms P21.Nonsymmetric.ChainInput.mk.sizeOf_spec
#print axioms P21.Nonsymmetric.ChainInput.mu
#print axioms P21.Nonsymmetric.ChainInput.mu_range
#print axioms P21.Nonsymmetric.ChainInput.noConfusion
#print axioms P21.Nonsymmetric.ChainInput.noConfusionType
#print axioms P21.Nonsymmetric.ChainInput.nu
#print axioms P21.Nonsymmetric.ChainInput.nu_range
#print axioms P21.Nonsymmetric.ChainInput.rec
#print axioms P21.Nonsymmetric.ChainInput.recOn
#print axioms P21.Nonsymmetric.ChainInput.values
#print axioms P21.Nonsymmetric.ColorCap.BoxInput
#print axioms P21.Nonsymmetric.ColorCap.BoxInput._sizeOf_1
#print axioms P21.Nonsymmetric.ColorCap.BoxInput._sizeOf_inst
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.b
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.b_pos
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.casesOn
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.ctorIdx
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.in_box_fire_unique
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.in_box_fire_unique._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.in_box_fire_unique._proof_1_3
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.in_box_fire_unique._proof_1_4
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.in_box_fire_unique._proof_1_5
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.in_box_fire_unique._proof_1_6
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.in_box_fire_unique._proof_1_7
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_in_box
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_in_box._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_10
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_11
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_12
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_13
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_14
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_15
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_16
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_3
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_4
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_5
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_6
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_7
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_8
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.initial_positive_firing._proof_1_9
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.m
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.m_pos
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.maximal_path
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.minor01_pos
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.minor02_pos
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.mk
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.mk._flat_ctor
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.mk.congr_simp
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.mk.inj
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.mk.injEq
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.mk.noConfusion
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.mk.sizeOf_spec
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.n
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.n_gt
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.noConfusion
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.noConfusionType
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.rec
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.recOn
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.row0
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.row1
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.row2
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.rows
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.rows._proof_1
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.rows.eq_1
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.rows_weight
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.sink_cover
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.sink_cover._proof_1_10
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.sink_cover._proof_1_11
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.sink_cover._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.sink_cover._proof_1_3
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.sink_cover._proof_1_4
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.sink_cover._proof_1_5
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.sink_cover._proof_1_6
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.sink_cover._proof_1_7
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.sink_cover._proof_1_8
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.sink_cover._proof_1_9
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.two_color12_not_sinkA
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.two_color12_not_sinkA._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.two_color12_not_sinkA._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.two_color12_not_sinkA._proof_1_3
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.two_color13_not_sinkB
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.two_color13_not_sinkB._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.two_color13_not_sinkB._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.upper
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.upper.eq_1
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.x
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.x_pos
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.y
#print axioms P21.Nonsymmetric.ColorCap.BoxInput.y_pos
#print axioms P21.Nonsymmetric.ColorCap.BoxPath
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.below
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.below.casesOn
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.below.nil
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.below.rec
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.below.snoc
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.brecOn
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.casesOn
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.endpoint
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.nil
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.rec
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.recOn
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.same_element
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.snoc
#print axioms P21.Nonsymmetric.ColorCap.BoxPath.weight_eq
#print axioms P21.Nonsymmetric.ColorCap.BoxPositiveExitStatement
#print axioms P21.Nonsymmetric.ColorCap.InBox
#print axioms P21.Nonsymmetric.ColorCap.MinimumOneStatement
#print axioms P21.Nonsymmetric.ColorCap.Point
#print axioms P21.Nonsymmetric.ColorCap.actual_of_nonnegative
#print axioms P21.Nonsymmetric.ColorCap.actual_three_arm_minimum
#print axioms P21.Nonsymmetric.ColorCap.arm_coordinate_cap
#print axioms P21.Nonsymmetric.ColorCap.arm_coordinate_cap._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.arm_coordinate_cap._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.arm_coordinate_cap._simp_1_3
#print axioms P21.Nonsymmetric.ColorCap.colorA_actual_minimum
#print axioms P21.Nonsymmetric.ColorCap.colorA_boxInput
#print axioms P21.Nonsymmetric.ColorCap.colorA_boxInput._proof_1
#print axioms P21.Nonsymmetric.ColorCap.colorA_boxInput._proof_2
#print axioms P21.Nonsymmetric.ColorCap.colorA_boxInput._proof_3
#print axioms P21.Nonsymmetric.ColorCap.colorA_boxInput._proof_4
#print axioms P21.Nonsymmetric.ColorCap.colorA_boxInput._proof_5
#print axioms P21.Nonsymmetric.ColorCap.colorA_boxInput._proof_6
#print axioms P21.Nonsymmetric.ColorCap.colorA_boxInput._proof_7
#print axioms P21.Nonsymmetric.ColorCap.colorA_boxInput._proof_8
#print axioms P21.Nonsymmetric.ColorCap.colorA_boxInput._proof_9
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds._proof_1_10
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds._proof_1_11
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds._proof_1_12
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds._proof_1_3
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds._proof_1_4
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds._proof_1_5
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds._proof_1_6
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds._proof_1_7
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds._proof_1_8
#print axioms P21.Nonsymmetric.ColorCap.colorA_class_bounds._proof_1_9
#print axioms P21.Nonsymmetric.ColorCap.colorA_companion_bounds
#print axioms P21.Nonsymmetric.ColorCap.colorA_companion_bounds._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.colorA_parameter_contradiction
#print axioms P21.Nonsymmetric.ColorCap.colorA_parameter_contradiction._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.colorA_parameters
#print axioms P21.Nonsymmetric.ColorCap.colorA_parameters._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.colorA_parameters._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.colorA_three_arm_contradiction_of_minbox
#print axioms P21.Nonsymmetric.ColorCap.colorA_three_arm_contradiction_of_minbox._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.colorB_actual_minimum
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_1
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_10
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_11
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_12
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_13
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_2
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_3
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_4
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_5
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_6
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_7
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_8
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput._proof_9
#print axioms P21.Nonsymmetric.ColorCap.colorB_boxInput.eq_1
#print axioms P21.Nonsymmetric.ColorCap.colorB_companion_bounds
#print axioms P21.Nonsymmetric.ColorCap.colorB_companion_bounds._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.colorB_parameter_contradiction
#print axioms P21.Nonsymmetric.ColorCap.colorB_parameter_contradiction._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.colorB_parameters
#print axioms P21.Nonsymmetric.ColorCap.colorB_parameters._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.colorB_parameters._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.colorB_three_arm_contradiction_of_minbox
#print axioms P21.Nonsymmetric.ColorCap.colorB_three_arm_contradiction_of_minbox._proof_1_3
#print axioms P21.Nonsymmetric.ColorCap.colorB_three_arm_contradiction_of_minbox._proof_1_4
#print axioms P21.Nonsymmetric.ColorCap.crossing_separator
#print axioms P21.Nonsymmetric.ColorCap.crossing_separator._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.failure_cone_mass
#print axioms P21.Nonsymmetric.ColorCap.failure_cone_mass._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.failure_cone_mass._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.failure_cone_mass._proof_1_3
#print axioms P21.Nonsymmetric.ColorCap.failure_cone_mass._proof_1_4
#print axioms P21.Nonsymmetric.ColorCap.fire
#print axioms P21.Nonsymmetric.ColorCap.fire.eq_1
#print axioms P21.Nonsymmetric.ColorCap.fire_weight
#print axioms P21.Nonsymmetric.ColorCap.lower_companion_impossible
#print axioms P21.Nonsymmetric.ColorCap.lower_companion_impossible._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.lower_companion_impossible._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.maximal_box_path
#print axioms P21.Nonsymmetric.ColorCap.maximal_box_path._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.maximal_box_path._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.minimal_positive_arm_box
#print axioms P21.Nonsymmetric.ColorCap.minimal_positive_arm_box._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.minimal_positive_arm_box._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.minimal_positive_level
#print axioms P21.Nonsymmetric.ColorCap.minimal_positive_level._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.one_color_sink_impossible
#print axioms P21.Nonsymmetric.ColorCap.one_color_sink_impossible._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.one_color_sink_impossible._proof_1_3
#print axioms P21.Nonsymmetric.ColorCap.one_color_sink_impossible._proof_1_4
#print axioms P21.Nonsymmetric.ColorCap.path_exit_contradiction
#print axioms P21.Nonsymmetric.ColorCap.path_exit_contradiction._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.positive_companion_failure
#print axioms P21.Nonsymmetric.ColorCap.positive_companion_failure._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.prefix_residue_antichain
#print axioms P21.Nonsymmetric.ColorCap.prefix_residue_antichain._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.prefix_residue_antichain._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.prefix_residue_antichain._proof_1_3
#print axioms P21.Nonsymmetric.ColorCap.prefix_residue_distinct
#print axioms P21.Nonsymmetric.ColorCap.prefix_residue_distinct._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.prefix_residue_distinct._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.prefix_residue_distinct._proof_1_3
#print axioms P21.Nonsymmetric.ColorCap.prefix_residue_distinct._proof_1_4
#print axioms P21.Nonsymmetric.ColorCap.prefix_residue_distinct._proof_1_5
#print axioms P21.Nonsymmetric.ColorCap.prefix_residue_distinct._proof_1_6
#print axioms P21.Nonsymmetric.ColorCap.relativeLattice
#print axioms P21.Nonsymmetric.ColorCap.relativeLattice._proof_1
#print axioms P21.Nonsymmetric.ColorCap.relativeLattice._proof_2
#print axioms P21.Nonsymmetric.ColorCap.relativeLattice._proof_3
#print axioms P21.Nonsymmetric.ColorCap.relative_lattice_level
#print axioms P21.Nonsymmetric.ColorCap.residue_slot_bound
#print axioms P21.Nonsymmetric.ColorCap.residue_slot_bound._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.same_element_positive_exit
#print axioms P21.Nonsymmetric.ColorCap.same_element_positive_exit._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.same_element_positive_exit._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.six_companion_failures
#print axioms P21.Nonsymmetric.ColorCap.six_companion_failures._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.six_companion_failures._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.socle_mem_of_actual_arm
#print axioms P21.Nonsymmetric.ColorCap.socle_mem_of_actual_arm._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.socle_mem_of_actual_arm._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.successful_prefix_separator
#print axioms P21.Nonsymmetric.ColorCap.three_arms_impossible_of_residuals
#print axioms P21.Nonsymmetric.ColorCap.top_face_positive_impossible
#print axioms P21.Nonsymmetric.ColorCap.top_face_positive_impossible._proof_1_1
#print axioms P21.Nonsymmetric.ColorCap.top_face_positive_impossible._proof_1_2
#print axioms P21.Nonsymmetric.ColorCap.weight
#print axioms P21.Nonsymmetric.ColorCap.weight.eq_1
#print axioms P21.Nonsymmetric.ColorCap.weight_add
#print axioms P21.Nonsymmetric.ColorCap.weight_sub
#print axioms P21.Nonsymmetric.ColorCap.weighted_certificate_impossible
#print axioms P21.Nonsymmetric.ColorCap.weighted_certificate_impossible._proof_1_1
#print axioms P21.Nonsymmetric.FourDistinctActualQRows
#print axioms P21.Nonsymmetric.FourDistinctActualQRows._sizeOf_1
#print axioms P21.Nonsymmetric.FourDistinctActualQRows._sizeOf_inst
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.casesOn
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.ctorIdx
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.distinct
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.mk
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.mk._flat_ctor
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.mk.inj
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.mk.injEq
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.mk.noConfusion
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.mk.sizeOf_spec
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.noConfusion
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.noConfusionType
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.rec
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.recOn
#print axioms P21.Nonsymmetric.FourDistinctActualQRows.row
#print axioms P21.Nonsymmetric.HerzogClassificationStatement
#print axioms P21.Nonsymmetric.HerzogCriticalData
#print axioms P21.Nonsymmetric.HerzogCriticalData._sizeOf_1
#print axioms P21.Nonsymmetric.HerzogCriticalData._sizeOf_inst
#print axioms P21.Nonsymmetric.HerzogCriticalData.a
#print axioms P21.Nonsymmetric.HerzogCriticalData.a_pos
#print axioms P21.Nonsymmetric.HerzogCriticalData.b
#print axioms P21.Nonsymmetric.HerzogCriticalData.b_pos
#print axioms P21.Nonsymmetric.HerzogCriticalData.casesOn
#print axioms P21.Nonsymmetric.HerzogCriticalData.coeff_rho
#print axioms P21.Nonsymmetric.HerzogCriticalData.critical
#print axioms P21.Nonsymmetric.HerzogCriticalData.critical_minimal
#print axioms P21.Nonsymmetric.HerzogCriticalData.ctorIdx
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA._proof_1
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA.eq_1
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_apery_formula
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_cyclic
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_gap
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_gap._proof_1_1
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_gap._proof_1_2
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_gap._proof_1_3
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_gap._proof_1_4
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_gap._proof_1_5
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_mem_tailPF
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_ne_fB
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_ne_fB._proof_1_1
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_ne_fB._proof_1_2
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_returns
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_returns._proof_1_1
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_returns._proof_1_2
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_returns._proof_1_3
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_returns._proof_1_4
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_returns._proof_1_5
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_returns._proof_1_6
#print axioms P21.Nonsymmetric.HerzogCriticalData.fA_returns._proof_1_7
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB.eq_1
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_apery_formula
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_cyclic
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_gap
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_gap._proof_1_1
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_gap._proof_1_2
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_gap._proof_1_3
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_gap._proof_1_4
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_gap._proof_1_5
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_mem_tailPF
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_returns
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_returns._proof_1_1
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_returns._proof_1_2
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_returns._proof_1_3
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_returns._proof_1_4
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_returns._proof_1_5
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_returns._proof_1_6
#print axioms P21.Nonsymmetric.HerzogCriticalData.fB_returns._proof_1_7
#print axioms P21.Nonsymmetric.HerzogCriticalData.fullData
#print axioms P21.Nonsymmetric.HerzogCriticalData.mk
#print axioms P21.Nonsymmetric.HerzogCriticalData.mk._flat_ctor
#print axioms P21.Nonsymmetric.HerzogCriticalData.mk.congr_simp
#print axioms P21.Nonsymmetric.HerzogCriticalData.mk.inj
#print axioms P21.Nonsymmetric.HerzogCriticalData.mk.injEq
#print axioms P21.Nonsymmetric.HerzogCriticalData.mk.noConfusion
#print axioms P21.Nonsymmetric.HerzogCriticalData.mk.sizeOf_spec
#print axioms P21.Nonsymmetric.HerzogCriticalData.noConfusion
#print axioms P21.Nonsymmetric.HerzogCriticalData.noConfusionType
#print axioms P21.Nonsymmetric.HerzogCriticalData.rec
#print axioms P21.Nonsymmetric.HerzogCriticalData.recOn
#print axioms P21.Nonsymmetric.HerzogCriticalData.relationCoeff
#print axioms P21.Nonsymmetric.HerzogCriticalData.relationCoeff.eq_1
#print axioms P21.Nonsymmetric.HerzogCriticalData.relationCoeff_pos
#print axioms P21.Nonsymmetric.HerzogCriticalData.relationCoeff_self
#print axioms P21.Nonsymmetric.HerzogCriticalData.relationCoeff_value
#print axioms P21.Nonsymmetric.HerzogCriticalData.relation_one
#print axioms P21.Nonsymmetric.HerzogCriticalData.relation_two
#print axioms P21.Nonsymmetric.HerzogCriticalData.relation_zero
#print axioms P21.Nonsymmetric.HerzogCriticalData.rho
#print axioms P21.Nonsymmetric.HerzogCriticalData.rho_eq
#print axioms P21.Nonsymmetric.HerzogCriticalData.rho_pos
#print axioms P21.Nonsymmetric.HerzogCriticalData.tailPF_eq_pair
#print axioms P21.Nonsymmetric.HerzogCriticalData.tailPF_eq_pair._simp_1_1
#print axioms P21.Nonsymmetric.HerzogCriticalData.tailPF_eq_pair._simp_1_2
#print axioms P21.Nonsymmetric.HerzogCriticalData.tailPF_subset_pair
#print axioms P21.Nonsymmetric.HerzogCriticalData.tailPF_subset_pair._proof_1_1
#print axioms P21.Nonsymmetric.HerzogCriticalData.tailPF_subset_pair._proof_1_2
#print axioms P21.Nonsymmetric.HerzogCriticalData.tailPF_subset_pair._proof_1_3
#print axioms P21.Nonsymmetric.IsArmA
#print axioms P21.Nonsymmetric.IsArmA.eq_1
#print axioms P21.Nonsymmetric.IsArmB
#print axioms P21.Nonsymmetric.IsArmB.eq_1
#print axioms P21.Nonsymmetric.IsSingleton
#print axioms P21.Nonsymmetric.IsSingleton.eq_1
#print axioms P21.Nonsymmetric.MatchedPairData
#print axioms P21.Nonsymmetric.MatchedPairData.P
#print axioms P21.Nonsymmetric.MatchedPairData.P_eq
#print axioms P21.Nonsymmetric.MatchedPairData.P_gt_a
#print axioms P21.Nonsymmetric.MatchedPairData.P_gt_a._proof_1_1
#print axioms P21.Nonsymmetric.MatchedPairData.P_gt_b
#print axioms P21.Nonsymmetric.MatchedPairData.P_gt_b._proof_1_1
#print axioms P21.Nonsymmetric.MatchedPairData.P_pos
#print axioms P21.Nonsymmetric.MatchedPairData.P_pos._proof_1_1
#print axioms P21.Nonsymmetric.MatchedPairData.R
#print axioms P21.Nonsymmetric.MatchedPairData.R_eq
#print axioms P21.Nonsymmetric.MatchedPairData.R_lt
#print axioms P21.Nonsymmetric.MatchedPairData.R_pos
#print axioms P21.Nonsymmetric.MatchedPairData.R_pos._proof_1_1
#print axioms P21.Nonsymmetric.MatchedPairData.T
#print axioms P21.Nonsymmetric.MatchedPairData.T_eq
#print axioms P21.Nonsymmetric.MatchedPairData.T_lt
#print axioms P21.Nonsymmetric.MatchedPairData.T_pos
#print axioms P21.Nonsymmetric.MatchedPairData.T_pos._proof_1_1
#print axioms P21.Nonsymmetric.MatchedPairData.W_eq
#print axioms P21.Nonsymmetric.MatchedPairData._sizeOf_1
#print axioms P21.Nonsymmetric.MatchedPairData._sizeOf_inst
#print axioms P21.Nonsymmetric.MatchedPairData.casesOn
#print axioms P21.Nonsymmetric.MatchedPairData.compA
#print axioms P21.Nonsymmetric.MatchedPairData.compB
#print axioms P21.Nonsymmetric.MatchedPairData.ctorIdx
#print axioms P21.Nonsymmetric.MatchedPairData.depth
#print axioms P21.Nonsymmetric.MatchedPairData.depth_a
#print axioms P21.Nonsymmetric.MatchedPairData.depth_b
#print axioms P21.Nonsymmetric.MatchedPairData.depth_pos
#print axioms P21.Nonsymmetric.MatchedPairData.gapJ
#print axioms P21.Nonsymmetric.MatchedPairData.gapJ_nonneg
#print axioms P21.Nonsymmetric.MatchedPairData.gapK
#print axioms P21.Nonsymmetric.MatchedPairData.gapK_nonneg
#print axioms P21.Nonsymmetric.MatchedPairData.mk
#print axioms P21.Nonsymmetric.MatchedPairData.mk._flat_ctor
#print axioms P21.Nonsymmetric.MatchedPairData.mk.inj
#print axioms P21.Nonsymmetric.MatchedPairData.mk.injEq
#print axioms P21.Nonsymmetric.MatchedPairData.mk.noConfusion
#print axioms P21.Nonsymmetric.MatchedPairData.mk.sizeOf_spec
#print axioms P21.Nonsymmetric.MatchedPairData.noConfusion
#print axioms P21.Nonsymmetric.MatchedPairData.noConfusionType
#print axioms P21.Nonsymmetric.MatchedPairData.qA_eq
#print axioms P21.Nonsymmetric.MatchedPairData.qB_eq
#print axioms P21.Nonsymmetric.MatchedPairData.rec
#print axioms P21.Nonsymmetric.MatchedPairData.recOn
#print axioms P21.Nonsymmetric.MatchedPairData.returnA_not_tail
#print axioms P21.Nonsymmetric.MatchedPairData.returnA_not_tail._proof_1_1
#print axioms P21.Nonsymmetric.MatchedPairData.returnB_not_tail
#print axioms P21.Nonsymmetric.MatchedPairData.returnB_not_tail._proof_1_1
#print axioms P21.Nonsymmetric.MinimalReturn
#print axioms P21.Nonsymmetric.MinimalReturn.L
#print axioms P21.Nonsymmetric.MinimalReturn.L_pos
#print axioms P21.Nonsymmetric.MinimalReturn.U
#print axioms P21.Nonsymmetric.MinimalReturn.U_nonneg
#print axioms P21.Nonsymmetric.MinimalReturn.V
#print axioms P21.Nonsymmetric.MinimalReturn.V_nonneg
#print axioms P21.Nonsymmetric.MinimalReturn._sizeOf_1
#print axioms P21.Nonsymmetric.MinimalReturn._sizeOf_inst
#print axioms P21.Nonsymmetric.MinimalReturn.casesOn
#print axioms P21.Nonsymmetric.MinimalReturn.ctorIdx
#print axioms P21.Nonsymmetric.MinimalReturn.equation
#print axioms P21.Nonsymmetric.MinimalReturn.minimal
#print axioms P21.Nonsymmetric.MinimalReturn.mk
#print axioms P21.Nonsymmetric.MinimalReturn.mk._flat_ctor
#print axioms P21.Nonsymmetric.MinimalReturn.mk.inj
#print axioms P21.Nonsymmetric.MinimalReturn.mk.injEq
#print axioms P21.Nonsymmetric.MinimalReturn.mk.noConfusion
#print axioms P21.Nonsymmetric.MinimalReturn.mk.sizeOf_spec
#print axioms P21.Nonsymmetric.MinimalReturn.noConfusion
#print axioms P21.Nonsymmetric.MinimalReturn.noConfusionType
#print axioms P21.Nonsymmetric.MinimalReturn.rec
#print axioms P21.Nonsymmetric.MinimalReturn.recOn
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData._sizeOf_1
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData._sizeOf_inst
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.casesOn
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.ctorIdx
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.distinct
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.mk
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.mk._flat_ctor
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.mk.congr_simp
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.mk.inj
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.mk.injEq
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.mk.noConfusion
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.mk.sizeOf_spec
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.noConfusion
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.noConfusionType
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.pf_exact
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.rec
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.recOn
#print axioms P21.Nonsymmetric.NonsymmetricHerzogData.toHerzogCriticalData
#print axioms P21.Nonsymmetric.NonsymmetricTail
#print axioms P21.Nonsymmetric.PathInput
#print axioms P21.Nonsymmetric.PathInput.A_eq
#print axioms P21.Nonsymmetric.PathInput.A_missing
#print axioms P21.Nonsymmetric.PathInput.B_eq
#print axioms P21.Nonsymmetric.PathInput.B_missing
#print axioms P21.Nonsymmetric.PathInput.R
#print axioms P21.Nonsymmetric.PathInput.R_range
#print axioms P21.Nonsymmetric.PathInput._sizeOf_1
#print axioms P21.Nonsymmetric.PathInput._sizeOf_inst
#print axioms P21.Nonsymmetric.PathInput.actual
#print axioms P21.Nonsymmetric.PathInput.boxW
#print axioms P21.Nonsymmetric.PathInput.cA
#print axioms P21.Nonsymmetric.PathInput.cB
#print axioms P21.Nonsymmetric.PathInput.cL
#print axioms P21.Nonsymmetric.PathInput.cR
#print axioms P21.Nonsymmetric.PathInput.casesOn
#print axioms P21.Nonsymmetric.PathInput.ctorIdx
#print axioms P21.Nonsymmetric.PathInput.distinct
#print axioms P21.Nonsymmetric.PathInput.ladder_left
#print axioms P21.Nonsymmetric.PathInput.ladder_middle
#print axioms P21.Nonsymmetric.PathInput.ladder_right
#print axioms P21.Nonsymmetric.PathInput.lambda
#print axioms P21.Nonsymmetric.PathInput.lambda_range
#print axioms P21.Nonsymmetric.PathInput.left_singleton
#print axioms P21.Nonsymmetric.PathInput.mk
#print axioms P21.Nonsymmetric.PathInput.mk._flat_ctor
#print axioms P21.Nonsymmetric.PathInput.mk.inj
#print axioms P21.Nonsymmetric.PathInput.mk.injEq
#print axioms P21.Nonsymmetric.PathInput.mk.noConfusion
#print axioms P21.Nonsymmetric.PathInput.mk.sizeOf_spec
#print axioms P21.Nonsymmetric.PathInput.noConfusion
#print axioms P21.Nonsymmetric.PathInput.noConfusionType
#print axioms P21.Nonsymmetric.PathInput.nu
#print axioms P21.Nonsymmetric.PathInput.nu_range
#print axioms P21.Nonsymmetric.PathInput.qA
#print axioms P21.Nonsymmetric.PathInput.qB
#print axioms P21.Nonsymmetric.PathInput.qL
#print axioms P21.Nonsymmetric.PathInput.qR
#print axioms P21.Nonsymmetric.PathInput.rec
#print axioms P21.Nonsymmetric.PathInput.recOn
#print axioms P21.Nonsymmetric.PathInput.right_singleton
#print axioms P21.Nonsymmetric.PathInput.values
#print axioms P21.Nonsymmetric.Realizes
#print axioms P21.Nonsymmetric.Realizes.eq_1
#print axioms P21.Nonsymmetric.Realizes.eq_2
#print axioms P21.Nonsymmetric.Realizes.eq_3
#print axioms P21.Nonsymmetric.Realizes.eq_4
#print axioms P21.Nonsymmetric.Realizes.eq_5
#print axioms P21.Nonsymmetric.Realizes.match_1
#print axioms P21.Nonsymmetric.RowLabel
#print axioms P21.Nonsymmetric.RowLabel.A
#print axioms P21.Nonsymmetric.RowLabel.B
#print axioms P21.Nonsymmetric.RowLabel.Compatible
#print axioms P21.Nonsymmetric.RowLabel.S
#print axioms P21.Nonsymmetric.RowLabel.Terminal
#print axioms P21.Nonsymmetric.RowLabel._sizeOf_1
#print axioms P21.Nonsymmetric.RowLabel._sizeOf_inst
#print axioms P21.Nonsymmetric.RowLabel.arm
#print axioms P21.Nonsymmetric.RowLabel.arm.elim
#print axioms P21.Nonsymmetric.RowLabel.arm.inj
#print axioms P21.Nonsymmetric.RowLabel.arm.injEq
#print axioms P21.Nonsymmetric.RowLabel.arm.noConfusion
#print axioms P21.Nonsymmetric.RowLabel.arm.sizeOf_spec
#print axioms P21.Nonsymmetric.RowLabel.casesOn
#print axioms P21.Nonsymmetric.RowLabel.chain
#print axioms P21.Nonsymmetric.RowLabel.chain.eq_1
#print axioms P21.Nonsymmetric.RowLabel.corner
#print axioms P21.Nonsymmetric.RowLabel.corner.elim
#print axioms P21.Nonsymmetric.RowLabel.corner.inj
#print axioms P21.Nonsymmetric.RowLabel.corner.injEq
#print axioms P21.Nonsymmetric.RowLabel.corner.noConfusion
#print axioms P21.Nonsymmetric.RowLabel.corner.sizeOf_spec
#print axioms P21.Nonsymmetric.RowLabel.ctorElim
#print axioms P21.Nonsymmetric.RowLabel.ctorElimType
#print axioms P21.Nonsymmetric.RowLabel.ctorIdx
#print axioms P21.Nonsymmetric.RowLabel.four_labels_classification
#print axioms P21.Nonsymmetric.RowLabel.instDecidableCompatible
#print axioms P21.Nonsymmetric.RowLabel.instDecidableTerminal
#print axioms P21.Nonsymmetric.RowLabel.noConfusion
#print axioms P21.Nonsymmetric.RowLabel.noConfusionType
#print axioms P21.Nonsymmetric.RowLabel.path
#print axioms P21.Nonsymmetric.RowLabel.path.eq_1
#print axioms P21.Nonsymmetric.RowLabel.proxyType
#print axioms P21.Nonsymmetric.RowLabel.proxyTypeEquiv
#print axioms P21.Nonsymmetric.RowLabel.rec
#print axioms P21.Nonsymmetric.RowLabel.recOn
#print axioms P21.Nonsymmetric.RowLabel.revDir
#print axioms P21.Nonsymmetric.RowLabel.revDir._proof_1
#print axioms P21.Nonsymmetric.RowLabel.reverse
#print axioms P21.Nonsymmetric.RowLabel.reverse.eq_1
#print axioms P21.Nonsymmetric.RowLabel.reverse.eq_2
#print axioms P21.Nonsymmetric.RowLabel.reverse.eq_3
#print axioms P21.Nonsymmetric.RowLabel.reverse_reverse
#print axioms P21.Nonsymmetric.RowLabel.rotateBack
#print axioms P21.Nonsymmetric.RowLabel.rotateBack.eq_1
#print axioms P21.Nonsymmetric.RowLabel.rotateBack.eq_2
#print axioms P21.Nonsymmetric.RowLabel.rotateBack.eq_3
#print axioms P21.Nonsymmetric.RowLabel.rotateBack.match_1
#print axioms P21.Nonsymmetric.RowLabel.rotate_chain
#print axioms P21.Nonsymmetric.RowLabel.rotate_path
#print axioms P21.Nonsymmetric.RowLabel.rotate_typeII
#print axioms P21.Nonsymmetric.RowLabel.singleton
#print axioms P21.Nonsymmetric.RowLabel.singleton.elim
#print axioms P21.Nonsymmetric.RowLabel.singleton.inj
#print axioms P21.Nonsymmetric.RowLabel.singleton.injEq
#print axioms P21.Nonsymmetric.RowLabel.singleton.noConfusion
#print axioms P21.Nonsymmetric.RowLabel.singleton.sizeOf_spec
#print axioms P21.Nonsymmetric.RowLabel.typeII
#print axioms P21.Nonsymmetric.RowLabel.typeII.eq_1
#print axioms P21.Nonsymmetric.SelectedTerminal
#print axioms P21.Nonsymmetric.TailPF
#print axioms P21.Nonsymmetric.TailPF.eq_1
#print axioms P21.Nonsymmetric.TerminalInputExists
#print axioms P21.Nonsymmetric.TerminalInputExists._proof_1
#print axioms P21.Nonsymmetric.TypeIIInput
#print axioms P21.Nonsymmetric.TypeIIInput.Ai_missing
#print axioms P21.Nonsymmetric.TypeIIInput.Ak_missing
#print axioms P21.Nonsymmetric.TypeIIInput.Bj_missing
#print axioms P21.Nonsymmetric.TypeIIInput._sizeOf_1
#print axioms P21.Nonsymmetric.TypeIIInput._sizeOf_inst
#print axioms P21.Nonsymmetric.TypeIIInput.actual
#print axioms P21.Nonsymmetric.TypeIIInput.boxW
#print axioms P21.Nonsymmetric.TypeIIInput.cAi
#print axioms P21.Nonsymmetric.TypeIIInput.cAk
#print axioms P21.Nonsymmetric.TypeIIInput.cBj
#print axioms P21.Nonsymmetric.TypeIIInput.cS
#print axioms P21.Nonsymmetric.TypeIIInput.casesOn
#print axioms P21.Nonsymmetric.TypeIIInput.ctorIdx
#print axioms P21.Nonsymmetric.TypeIIInput.distinct
#print axioms P21.Nonsymmetric.TypeIIInput.lambda
#print axioms P21.Nonsymmetric.TypeIIInput.lambda_range
#print axioms P21.Nonsymmetric.TypeIIInput.mk
#print axioms P21.Nonsymmetric.TypeIIInput.mk._flat_ctor
#print axioms P21.Nonsymmetric.TypeIIInput.mk.inj
#print axioms P21.Nonsymmetric.TypeIIInput.mk.injEq
#print axioms P21.Nonsymmetric.TypeIIInput.mk.noConfusion
#print axioms P21.Nonsymmetric.TypeIIInput.mk.sizeOf_spec
#print axioms P21.Nonsymmetric.TypeIIInput.mu
#print axioms P21.Nonsymmetric.TypeIIInput.mu_range
#print axioms P21.Nonsymmetric.TypeIIInput.noConfusion
#print axioms P21.Nonsymmetric.TypeIIInput.noConfusionType
#print axioms P21.Nonsymmetric.TypeIIInput.nu
#print axioms P21.Nonsymmetric.TypeIIInput.nu_range
#print axioms P21.Nonsymmetric.TypeIIInput.qS
#print axioms P21.Nonsymmetric.TypeIIInput.rec
#print axioms P21.Nonsymmetric.TypeIIInput.recOn
#print axioms P21.Nonsymmetric.TypeIIInput.singleton
#print axioms P21.Nonsymmetric.TypeIIInput.singleton_row
#print axioms P21.Nonsymmetric.TypeIIInput.values
#print axioms P21.Nonsymmetric.TypeIIInput.values._proof_1
#print axioms P21.Nonsymmetric.actual_AA_cyclic
#print axioms P21.Nonsymmetric.actual_AA_exclusions
#print axioms P21.Nonsymmetric.actual_AA_exclusions._proof_1_1
#print axioms P21.Nonsymmetric.actual_AA_exclusions._proof_1_2
#print axioms P21.Nonsymmetric.actual_AA_no_two_singletons
#print axioms P21.Nonsymmetric.actual_AB_excludes_endpoints
#print axioms P21.Nonsymmetric.actual_AB_excludes_endpoints._simp_1_1
#print axioms P21.Nonsymmetric.actual_AB_excludes_endpoints_zero
#print axioms P21.Nonsymmetric.actual_AB_excludes_endpoints_zero._proof_1_1
#print axioms P21.Nonsymmetric.actual_AB_excludes_endpoints_zero._proof_1_2
#print axioms P21.Nonsymmetric.actual_A_box
#print axioms P21.Nonsymmetric.actual_BA_excludes_middle
#print axioms P21.Nonsymmetric.actual_BA_excludes_middle_zero
#print axioms P21.Nonsymmetric.actual_BA_excludes_middle_zero._proof_1_1
#print axioms P21.Nonsymmetric.actual_BA_excludes_middle_zero._proof_1_2
#print axioms P21.Nonsymmetric.actual_BA_excludes_middle_zero._proof_1_3
#print axioms P21.Nonsymmetric.actual_BA_excludes_middle_zero._proof_1_4
#print axioms P21.Nonsymmetric.actual_BB_cyclic
#print axioms P21.Nonsymmetric.actual_BB_no_two_singletons
#print axioms P21.Nonsymmetric.actual_B_box
#print axioms P21.Nonsymmetric.actual_label_exists
#print axioms P21.Nonsymmetric.actual_labeling_exists
#print axioms P21.Nonsymmetric.actual_labels_compatible
#print axioms P21.Nonsymmetric.actual_labels_compatible._proof_1_1
#print axioms P21.Nonsymmetric.actual_labels_terminal
#print axioms P21.Nonsymmetric.actual_matched_data
#print axioms P21.Nonsymmetric.actual_matched_data._proof_1_1
#print axioms P21.Nonsymmetric.actual_matched_data._proof_1_2
#print axioms P21.Nonsymmetric.actual_matched_data._proof_1_3
#print axioms P21.Nonsymmetric.actual_matched_data._proof_1_4
#print axioms P21.Nonsymmetric.actual_matched_data._proof_1_5
#print axioms P21.Nonsymmetric.actual_matched_data._proof_1_6
#print axioms P21.Nonsymmetric.actual_matched_depths_equal
#print axioms P21.Nonsymmetric.actual_matched_depths_equal._proof_1_1
#print axioms P21.Nonsymmetric.actual_matched_depths_equal._proof_1_2
#print axioms P21.Nonsymmetric.actual_matched_depths_equal._proof_1_3
#print axioms P21.Nonsymmetric.actual_matched_depths_equal._proof_1_4
#print axioms P21.Nonsymmetric.actual_matched_depths_equal._proof_1_5
#print axioms P21.Nonsymmetric.actual_matched_depths_equal._proof_1_6
#print axioms P21.Nonsymmetric.actual_matched_depths_equal._proof_1_7
#print axioms P21.Nonsymmetric.actual_matched_exclusions
#print axioms P21.Nonsymmetric.actual_matched_exclusions._proof_1_3
#print axioms P21.Nonsymmetric.actual_matched_exclusions._proof_1_4
#print axioms P21.Nonsymmetric.actual_row_atlas
#print axioms P21.Nonsymmetric.actual_sub_copies
#print axioms P21.Nonsymmetric.actual_terminal_input_exists
#print axioms P21.Nonsymmetric.actual_three_A_excluded
#print axioms P21.Nonsymmetric.actual_three_A_excluded._proof_1_1
#print axioms P21.Nonsymmetric.actual_three_B_excluded
#print axioms P21.Nonsymmetric.actual_three_B_excluded._proof_1_1
#print axioms P21.Nonsymmetric.armA_not_singleton
#print axioms P21.Nonsymmetric.armA_returns
#print axioms P21.Nonsymmetric.armA_returns._proof_1_1
#print axioms P21.Nonsymmetric.armA_returns._proof_1_2
#print axioms P21.Nonsymmetric.armA_returns._proof_1_3
#print axioms P21.Nonsymmetric.armA_returns._proof_1_4
#print axioms P21.Nonsymmetric.armA_returns._proof_1_5
#print axioms P21.Nonsymmetric.armA_returns._proof_1_6
#print axioms P21.Nonsymmetric.armB_not_singleton
#print axioms P21.Nonsymmetric.armB_returns
#print axioms P21.Nonsymmetric.armB_returns._proof_1_1
#print axioms P21.Nonsymmetric.armB_returns._proof_1_2
#print axioms P21.Nonsymmetric.armB_returns._proof_1_3
#print axioms P21.Nonsymmetric.armB_returns._proof_1_4
#print axioms P21.Nonsymmetric.armB_returns._proof_1_5
#print axioms P21.Nonsymmetric.armB_returns._proof_1_6
#print axioms P21.Nonsymmetric.arm_complement_box
#print axioms P21.Nonsymmetric.arm_complement_pair
#print axioms P21.Nonsymmetric.arm_complement_unique
#print axioms P21.Nonsymmetric.arm_depth_bound
#print axioms P21.Nonsymmetric.arm_depth_bound._proof_1_1
#print axioms P21.Nonsymmetric.arm_depth_bound._proof_1_2
#print axioms P21.Nonsymmetric.both_corners_excluded
#print axioms P21.Nonsymmetric.chain_exact_input
#print axioms P21.Nonsymmetric.chain_exact_input._proof_1_10
#print axioms P21.Nonsymmetric.chain_exact_input._proof_1_11
#print axioms P21.Nonsymmetric.chain_exact_input._proof_1_12
#print axioms P21.Nonsymmetric.chain_exact_input._proof_1_5
#print axioms P21.Nonsymmetric.chain_exact_input._proof_1_8
#print axioms P21.Nonsymmetric.chain_exact_input._proof_1_9
#print axioms P21.Nonsymmetric.chain_exact_input.match_1_1
#print axioms P21.Nonsymmetric.chain_exact_input.match_1_3
#print axioms P21.Nonsymmetric.chain_exact_input.match_1_6
#print axioms P21.Nonsymmetric.chain_exact_input_independent
#print axioms P21.Nonsymmetric.cofinite_common_divisor
#print axioms P21.Nonsymmetric.cofinite_common_divisor._proof_1_1
#print axioms P21.Nonsymmetric.complement_antichain
#print axioms P21.Nonsymmetric.corner_A_same_arm_excluded
#print axioms P21.Nonsymmetric.corner_A_singleton_excluded
#print axioms P21.Nonsymmetric.corner_A_singleton_excluded._proof_1_1
#print axioms P21.Nonsymmetric.corner_A_singleton_excluded._proof_1_2
#print axioms P21.Nonsymmetric.corner_B_same_arm_excluded
#print axioms P21.Nonsymmetric.corner_B_singleton_excluded
#print axioms P21.Nonsymmetric.corner_B_singleton_excluded._proof_1_1
#print axioms P21.Nonsymmetric.corner_B_singleton_excluded._proof_1_2
#print axioms P21.Nonsymmetric.critical_box_unique
#print axioms P21.Nonsymmetric.critical_box_unique._proof_1_2
#print axioms P21.Nonsymmetric.critical_box_unique._proof_1_3
#print axioms P21.Nonsymmetric.critical_box_unique._proof_1_4
#print axioms P21.Nonsymmetric.critical_kernel_box_zero
#print axioms P21.Nonsymmetric.critical_kernel_box_zero._proof_1_1
#print axioms P21.Nonsymmetric.critical_kernel_box_zero._proof_1_10
#print axioms P21.Nonsymmetric.critical_kernel_box_zero._proof_1_3
#print axioms P21.Nonsymmetric.critical_kernel_box_zero._proof_1_4
#print axioms P21.Nonsymmetric.critical_kernel_box_zero._proof_1_5
#print axioms P21.Nonsymmetric.critical_kernel_box_zero._proof_1_6
#print axioms P21.Nonsymmetric.critical_kernel_box_zero._proof_1_7
#print axioms P21.Nonsymmetric.critical_kernel_box_zero._proof_1_8
#print axioms P21.Nonsymmetric.critical_kernel_box_zero._proof_1_9
#print axioms P21.Nonsymmetric.critical_le_of_single_positive
#print axioms P21.Nonsymmetric.critical_le_of_single_positive._proof_1_2
#print axioms P21.Nonsymmetric.critical_le_of_single_positive._proof_1_3
#print axioms P21.Nonsymmetric.critical_le_of_two
#print axioms P21.Nonsymmetric.critical_other_pos
#print axioms P21.Nonsymmetric.critical_other_pos._proof_1_1
#print axioms P21.Nonsymmetric.critical_pair_bound
#print axioms P21.Nonsymmetric.critical_pair_bound._proof_1_1
#print axioms P21.Nonsymmetric.critical_pair_bound._proof_1_2
#print axioms P21.Nonsymmetric.critical_pair_bound._proof_1_3
#print axioms P21.Nonsymmetric.critical_pair_bound._proof_1_4
#print axioms P21.Nonsymmetric.critical_pair_lower_bound
#print axioms P21.Nonsymmetric.critical_pair_lower_bound._proof_1_1
#print axioms P21.Nonsymmetric.cyclePerm
#print axioms P21.Nonsymmetric.cyclePerm._proof_1
#print axioms P21.Nonsymmetric.cyclePerm._proof_2
#print axioms P21.Nonsymmetric.cyclePerm.eq_1
#print axioms P21.Nonsymmetric.cyclic_distinct
#print axioms P21.Nonsymmetric.distinct_complements_not_one_ray
#print axioms P21.Nonsymmetric.equal_label_equal_row
#print axioms P21.Nonsymmetric.equal_level_matching
#print axioms P21.Nonsymmetric.equal_level_matching._proof_1_1
#print axioms P21.Nonsymmetric.equal_level_matching._proof_1_2
#print axioms P21.Nonsymmetric.equal_level_matching._proof_1_3
#print axioms P21.Nonsymmetric.equal_level_matching._proof_1_4
#print axioms P21.Nonsymmetric.equal_level_matching._proof_1_5
#print axioms P21.Nonsymmetric.equal_level_matching._proof_1_6
#print axioms P21.Nonsymmetric.equal_level_matching._proof_1_7
#print axioms P21.Nonsymmetric.equal_level_matching._proof_1_8
#print axioms P21.Nonsymmetric.fA_return_formula
#print axioms P21.Nonsymmetric.fB_return_formula
#print axioms P21.Nonsymmetric.four_mem
#print axioms P21.Nonsymmetric.four_return_caps
#print axioms P21.Nonsymmetric.four_return_caps._proof_1_1
#print axioms P21.Nonsymmetric.four_return_caps._proof_1_2
#print axioms P21.Nonsymmetric.frobenius_le_higher_corner
#print axioms P21.Nonsymmetric.frobenius_le_higher_corner._proof_1_1
#print axioms P21.Nonsymmetric.frobenius_return_caps
#print axioms P21.Nonsymmetric.frobenius_return_caps._proof_1_1
#print axioms P21.Nonsymmetric.frobenius_return_caps._proof_1_2
#print axioms P21.Nonsymmetric.frobenius_return_caps._proof_1_3
#print axioms P21.Nonsymmetric.frobenius_return_caps._proof_1_4
#print axioms P21.Nonsymmetric.frobenius_return_caps._proof_1_5
#print axioms P21.Nonsymmetric.frobenius_return_caps._proof_1_6
#print axioms P21.Nonsymmetric.full_return_coordinate_zero
#print axioms P21.Nonsymmetric.gap_sub_multiple
#print axioms P21.Nonsymmetric.herzog_L_gap
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_1
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_10
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_11
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_12
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_13
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_2
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_3
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_4
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_5
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_6
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_7
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_8
#print axioms P21.Nonsymmetric.herzog_L_gap._proof_1_9
#print axioms P21.Nonsymmetric.herzog_apery_L
#print axioms P21.Nonsymmetric.herzog_apery_L._proof_1_1
#print axioms P21.Nonsymmetric.herzog_apery_L._proof_1_2
#print axioms P21.Nonsymmetric.herzog_apery_L._proof_1_3
#print axioms P21.Nonsymmetric.herzog_apery_L._proof_1_4
#print axioms P21.Nonsymmetric.herzog_apery_L._proof_1_5
#print axioms P21.Nonsymmetric.herzog_apery_L._proof_1_6
#print axioms P21.Nonsymmetric.herzog_apery_L._proof_1_7
#print axioms P21.Nonsymmetric.herzog_apery_L._proof_1_8
#print axioms P21.Nonsymmetric.herzog_arm_missing
#print axioms P21.Nonsymmetric.herzog_arm_missing._proof_1_1
#print axioms P21.Nonsymmetric.herzog_classification
#print axioms P21.Nonsymmetric.herzog_critical_exists
#print axioms P21.Nonsymmetric.herzog_critical_exists._proof_1_1
#print axioms P21.Nonsymmetric.herzog_critical_exists._proof_1_2
#print axioms P21.Nonsymmetric.herzog_critical_exists._proof_1_3
#print axioms P21.Nonsymmetric.herzog_critical_exists._proof_1_4
#print axioms P21.Nonsymmetric.herzog_critical_exists._proof_1_5
#print axioms P21.Nonsymmetric.herzog_critical_exists._proof_1_6
#print axioms P21.Nonsymmetric.herzog_critical_exists._proof_1_7
#print axioms P21.Nonsymmetric.herzog_critical_exists._proof_1_8
#print axioms P21.Nonsymmetric.herzog_critical_exists._proof_1_9
#print axioms P21.Nonsymmetric.herzog_critical_le_int
#print axioms P21.Nonsymmetric.herzog_critical_le_int._proof_1_1
#print axioms P21.Nonsymmetric.herzog_packet_le
#print axioms P21.Nonsymmetric.herzog_packet_le._proof_1_1
#print axioms P21.Nonsymmetric.herzog_packet_le._proof_1_2
#print axioms P21.Nonsymmetric.herzog_packet_le._proof_1_3
#print axioms P21.Nonsymmetric.herzog_packet_le._proof_1_4
#print axioms P21.Nonsymmetric.herzog_packet_le._proof_1_5
#print axioms P21.Nonsymmetric.herzog_packet_le._proof_1_6
#print axioms P21.Nonsymmetric.herzog_packet_le._proof_1_7
#print axioms P21.Nonsymmetric.herzog_three_mem
#print axioms P21.Nonsymmetric.higher_corner_excluded
#print axioms P21.Nonsymmetric.higher_corner_excluded._proof_1_1
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_1
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_10
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_11
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_12
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_13
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_2
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_3
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_4
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_5
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_6
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_7
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_8
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq._proof_9
#print axioms P21.Nonsymmetric.instDecidableEqRowLabel.decEq.match_1
#print axioms P21.Nonsymmetric.instFintypeRowLabel
#print axioms P21.Nonsymmetric.instFintypeRowLabel.match_3
#print axioms P21.Nonsymmetric.instFintypeRowLabel.match_5
#print axioms P21.Nonsymmetric.integerValue
#print axioms P21.Nonsymmetric.integerValue.eq_1
#print axioms P21.Nonsymmetric.integer_kernel_basis
#print axioms P21.Nonsymmetric.integer_kernel_basis._proof_1_1
#print axioms P21.Nonsymmetric.integer_kernel_basis._proof_1_2
#print axioms P21.Nonsymmetric.integer_kernel_span
#print axioms P21.Nonsymmetric.integer_kernel_span._proof_1_4
#print axioms P21.Nonsymmetric.integer_kernel_span._simp_1_1
#print axioms P21.Nonsymmetric.kernelRowJ
#print axioms P21.Nonsymmetric.kernelRowJ._proof_1
#print axioms P21.Nonsymmetric.kernelRowJ.eq_1
#print axioms P21.Nonsymmetric.kernelRowJ_mem
#print axioms P21.Nonsymmetric.kernelRowK
#print axioms P21.Nonsymmetric.kernelRowK.eq_1
#print axioms P21.Nonsymmetric.kernelRowK_mem
#print axioms P21.Nonsymmetric.kernel_minor_pos
#print axioms P21.Nonsymmetric.kernel_rows_independent
#print axioms P21.Nonsymmetric.kernel_span_rat
#print axioms P21.Nonsymmetric.matched_kernel_box_zero
#print axioms P21.Nonsymmetric.matched_kernel_box_zero._proof_1_1
#print axioms P21.Nonsymmetric.matched_kernel_box_zero._proof_1_10
#print axioms P21.Nonsymmetric.matched_kernel_box_zero._proof_1_11
#print axioms P21.Nonsymmetric.matched_kernel_box_zero._proof_1_2
#print axioms P21.Nonsymmetric.matched_kernel_box_zero._proof_1_3
#print axioms P21.Nonsymmetric.matched_kernel_box_zero._proof_1_4
#print axioms P21.Nonsymmetric.matched_kernel_box_zero._proof_1_5
#print axioms P21.Nonsymmetric.matched_kernel_box_zero._proof_1_6
#print axioms P21.Nonsymmetric.matched_kernel_box_zero._proof_1_7
#print axioms P21.Nonsymmetric.matched_kernel_box_zero._proof_1_8
#print axioms P21.Nonsymmetric.matched_kernel_box_zero._proof_1_9
#print axioms P21.Nonsymmetric.matched_pair_data
#print axioms P21.Nonsymmetric.matched_pair_data._proof_1_1
#print axioms P21.Nonsymmetric.matched_pair_data._proof_1_2
#print axioms P21.Nonsymmetric.matched_pair_excludes_A_one
#print axioms P21.Nonsymmetric.matched_pair_excludes_A_one._proof_1_1
#print axioms P21.Nonsymmetric.matched_pair_excludes_A_one._proof_1_2
#print axioms P21.Nonsymmetric.matched_pair_excludes_B_two
#print axioms P21.Nonsymmetric.matched_pair_excludes_B_two._proof_1_1
#print axioms P21.Nonsymmetric.matched_pair_excludes_B_two._proof_1_2
#print axioms P21.Nonsymmetric.matched_pair_no_singleton
#print axioms P21.Nonsymmetric.matched_pair_no_singleton._proof_1_1
#print axioms P21.Nonsymmetric.matched_pair_no_singleton._proof_1_10
#print axioms P21.Nonsymmetric.matched_pair_no_singleton._proof_1_11
#print axioms P21.Nonsymmetric.matched_pair_no_singleton._proof_1_2
#print axioms P21.Nonsymmetric.matched_pair_no_singleton._proof_1_3
#print axioms P21.Nonsymmetric.matched_pair_no_singleton._proof_1_4
#print axioms P21.Nonsymmetric.matched_pair_no_singleton._proof_1_5
#print axioms P21.Nonsymmetric.matched_pair_no_singleton._proof_1_6
#print axioms P21.Nonsymmetric.matched_pair_no_singleton._proof_1_7
#print axioms P21.Nonsymmetric.matched_pair_no_singleton._proof_1_8
#print axioms P21.Nonsymmetric.matched_pair_no_singleton._proof_1_9
#print axioms P21.Nonsymmetric.matched_pair_sync
#print axioms P21.Nonsymmetric.matched_pair_sync._proof_1_1
#print axioms P21.Nonsymmetric.matched_pair_sync._proof_1_2
#print axioms P21.Nonsymmetric.matched_pair_sync._proof_1_3
#print axioms P21.Nonsymmetric.matched_pair_sync._proof_1_4
#print axioms P21.Nonsymmetric.matched_pair_sync._proof_1_5
#print axioms P21.Nonsymmetric.matched_pair_sync._proof_1_6
#print axioms P21.Nonsymmetric.maximal_gap_along_direction
#print axioms P21.Nonsymmetric.maximal_gap_along_direction._proof_1_1
#print axioms P21.Nonsymmetric.maximal_gap_along_direction._proof_1_2
#print axioms P21.Nonsymmetric.maximal_gap_along_direction._proof_1_3
#print axioms P21.Nonsymmetric.maximal_gap_along_direction._proof_1_4
#print axioms P21.Nonsymmetric.minimal_return_exists
#print axioms P21.Nonsymmetric.minimal_return_exists._proof_1_1
#print axioms P21.Nonsymmetric.minimal_return_exists._proof_1_2
#print axioms P21.Nonsymmetric.minimal_return_exists._proof_1_3
#print axioms P21.Nonsymmetric.minimal_return_exists._proof_1_4
#print axioms P21.Nonsymmetric.minimal_return_exists._proof_1_5
#print axioms P21.Nonsymmetric.missing_complement_bound
#print axioms P21.Nonsymmetric.missing_complement_bound._proof_1_1
#print axioms P21.Nonsymmetric.missing_complement_bound._proof_1_4
#print axioms P21.Nonsymmetric.missing_complement_zero
#print axioms P21.Nonsymmetric.mixed_A_not_singleton
#print axioms P21.Nonsymmetric.mixed_B_not_singleton
#print axioms P21.Nonsymmetric.mixed_left_complement_geometry
#print axioms P21.Nonsymmetric.mixed_left_complement_geometry._proof_1_2
#print axioms P21.Nonsymmetric.mixed_left_complement_geometry._proof_1_3
#print axioms P21.Nonsymmetric.mixed_left_complement_geometry._proof_1_4
#print axioms P21.Nonsymmetric.mixed_left_complement_geometry._proof_1_5
#print axioms P21.Nonsymmetric.mixed_left_complement_geometry._proof_1_6
#print axioms P21.Nonsymmetric.mixed_left_complement_geometry._proof_1_7
#print axioms P21.Nonsymmetric.mixed_left_kernel_coefficients
#print axioms P21.Nonsymmetric.mixed_left_kernel_coefficients._proof_1_1
#print axioms P21.Nonsymmetric.mixed_left_kernel_coefficients._proof_1_2
#print axioms P21.Nonsymmetric.mixed_left_kernel_coefficients._proof_1_3
#print axioms P21.Nonsymmetric.mixed_left_kernel_coefficients._proof_1_4
#print axioms P21.Nonsymmetric.mixed_left_kernel_coefficients._proof_1_5
#print axioms P21.Nonsymmetric.mixed_left_kernel_coefficients._proof_1_6
#print axioms P21.Nonsymmetric.mixed_left_kernel_coefficients._proof_1_7
#print axioms P21.Nonsymmetric.mixed_left_kernel_coefficients._proof_1_8
#print axioms P21.Nonsymmetric.mixed_left_no_first_singleton
#print axioms P21.Nonsymmetric.mixed_left_no_first_singleton._proof_1_3
#print axioms P21.Nonsymmetric.mixed_left_no_first_singleton._proof_1_4
#print axioms P21.Nonsymmetric.mixed_left_no_first_singleton._proof_1_5
#print axioms P21.Nonsymmetric.mixed_left_no_first_singleton._proof_1_6
#print axioms P21.Nonsymmetric.mixed_left_no_first_singleton.match_1_1
#print axioms P21.Nonsymmetric.mixed_left_no_last_singleton
#print axioms P21.Nonsymmetric.mixed_left_no_last_singleton._proof_1_3
#print axioms P21.Nonsymmetric.mixed_left_no_last_singleton._proof_1_4
#print axioms P21.Nonsymmetric.mixed_left_no_last_singleton._proof_1_5
#print axioms P21.Nonsymmetric.mixed_left_no_last_singleton._proof_1_6
#print axioms P21.Nonsymmetric.mixed_left_no_last_singleton.match_1_1
#print axioms P21.Nonsymmetric.mixed_right_complement_geometry
#print axioms P21.Nonsymmetric.mixed_right_complement_geometry._proof_1_2
#print axioms P21.Nonsymmetric.mixed_right_complement_geometry._proof_1_3
#print axioms P21.Nonsymmetric.mixed_right_complement_geometry._proof_1_4
#print axioms P21.Nonsymmetric.mixed_right_complement_geometry._proof_1_5
#print axioms P21.Nonsymmetric.mixed_right_complement_geometry._proof_1_6
#print axioms P21.Nonsymmetric.mixed_right_complement_geometry._proof_1_7
#print axioms P21.Nonsymmetric.mixed_right_complement_geometry._proof_1_8
#print axioms P21.Nonsymmetric.mixed_right_completed_W
#print axioms P21.Nonsymmetric.mixed_right_completed_W._proof_1_1
#print axioms P21.Nonsymmetric.mixed_right_completed_W._proof_1_2
#print axioms P21.Nonsymmetric.mixed_right_completed_W._proof_1_3
#print axioms P21.Nonsymmetric.mixed_right_kernel_coefficients
#print axioms P21.Nonsymmetric.mixed_right_kernel_coefficients._proof_1_1
#print axioms P21.Nonsymmetric.mixed_right_kernel_coefficients._proof_1_10
#print axioms P21.Nonsymmetric.mixed_right_kernel_coefficients._proof_1_2
#print axioms P21.Nonsymmetric.mixed_right_kernel_coefficients._proof_1_3
#print axioms P21.Nonsymmetric.mixed_right_kernel_coefficients._proof_1_4
#print axioms P21.Nonsymmetric.mixed_right_kernel_coefficients._proof_1_5
#print axioms P21.Nonsymmetric.mixed_right_kernel_coefficients._proof_1_6
#print axioms P21.Nonsymmetric.mixed_right_kernel_coefficients._proof_1_7
#print axioms P21.Nonsymmetric.mixed_right_kernel_coefficients._proof_1_8
#print axioms P21.Nonsymmetric.mixed_right_kernel_coefficients._proof_1_9
#print axioms P21.Nonsymmetric.mixed_right_next_complement_geometry
#print axioms P21.Nonsymmetric.mixed_right_next_complement_geometry._proof_1_10
#print axioms P21.Nonsymmetric.mixed_right_next_complement_geometry._proof_1_2
#print axioms P21.Nonsymmetric.mixed_right_next_complement_geometry._proof_1_3
#print axioms P21.Nonsymmetric.mixed_right_next_complement_geometry._proof_1_4
#print axioms P21.Nonsymmetric.mixed_right_next_complement_geometry._proof_1_5
#print axioms P21.Nonsymmetric.mixed_right_next_complement_geometry._proof_1_6
#print axioms P21.Nonsymmetric.mixed_right_next_complement_geometry._proof_1_7
#print axioms P21.Nonsymmetric.mixed_right_next_complement_geometry._proof_1_8
#print axioms P21.Nonsymmetric.mixed_right_next_complement_geometry._proof_1_9
#print axioms P21.Nonsymmetric.mixed_right_next_kernel_coefficients
#print axioms P21.Nonsymmetric.mixed_right_next_kernel_coefficients._proof_1_1
#print axioms P21.Nonsymmetric.mixed_right_next_kernel_coefficients._proof_1_10
#print axioms P21.Nonsymmetric.mixed_right_next_kernel_coefficients._proof_1_2
#print axioms P21.Nonsymmetric.mixed_right_next_kernel_coefficients._proof_1_3
#print axioms P21.Nonsymmetric.mixed_right_next_kernel_coefficients._proof_1_4
#print axioms P21.Nonsymmetric.mixed_right_next_kernel_coefficients._proof_1_5
#print axioms P21.Nonsymmetric.mixed_right_next_kernel_coefficients._proof_1_6
#print axioms P21.Nonsymmetric.mixed_right_next_kernel_coefficients._proof_1_7
#print axioms P21.Nonsymmetric.mixed_right_next_kernel_coefficients._proof_1_8
#print axioms P21.Nonsymmetric.mixed_right_next_kernel_coefficients._proof_1_9
#print axioms P21.Nonsymmetric.mixed_right_no_middle_singleton
#print axioms P21.Nonsymmetric.mixed_right_no_middle_singleton._proof_1_1
#print axioms P21.Nonsymmetric.mixed_right_no_middle_singleton._proof_1_2
#print axioms P21.Nonsymmetric.mixed_right_no_middle_singleton._proof_1_3
#print axioms P21.Nonsymmetric.next
#print axioms P21.Nonsymmetric.next._proof_1
#print axioms P21.Nonsymmetric.next.eq_1
#print axioms P21.Nonsymmetric.no_two_singletons_of_three_directions
#print axioms P21.Nonsymmetric.no_two_singletons_of_three_directions._proof_1_1
#print axioms P21.Nonsymmetric.nonsymmetric_Q_ge_four_of_colorcap_residuals
#print axioms P21.Nonsymmetric.nonsymmetric_herzog_exists
#print axioms P21.Nonsymmetric.nonsymmetric_herzog_primitive_exists
#print axioms P21.Nonsymmetric.nonsymmetric_selected_four_of_colorcap_residuals
#print axioms P21.Nonsymmetric.ordered_realization
#print axioms P21.Nonsymmetric.pair_nonnegative_mem
#print axioms P21.Nonsymmetric.path_exact_input
#print axioms P21.Nonsymmetric.path_exact_input._proof_1_1
#print axioms P21.Nonsymmetric.path_exact_input._proof_1_2
#print axioms P21.Nonsymmetric.path_exact_input._proof_1_3
#print axioms P21.Nonsymmetric.path_exact_input._proof_1_4
#print axioms P21.Nonsymmetric.path_exact_input._proof_1_5
#print axioms P21.Nonsymmetric.path_pair_data
#print axioms P21.Nonsymmetric.path_pair_data._proof_1_1
#print axioms P21.Nonsymmetric.path_pair_data._proof_1_2
#print axioms P21.Nonsymmetric.perm_last_two
#print axioms P21.Nonsymmetric.pf_antichain
#print axioms P21.Nonsymmetric.pf_antichain._proof_1_1
#print axioms P21.Nonsymmetric.pf_ray_unique
#print axioms P21.Nonsymmetric.prev
#print axioms P21.Nonsymmetric.prev.eq_1
#print axioms P21.Nonsymmetric.primitive_generator_formulas
#print axioms P21.Nonsymmetric.primitive_generator_minors
#print axioms P21.Nonsymmetric.primitive_generator_minors._proof_1_1
#print axioms P21.Nonsymmetric.primitive_generator_minors._proof_1_2
#print axioms P21.Nonsymmetric.primitive_generator_minors._proof_1_3
#print axioms P21.Nonsymmetric.primitive_generator_minors._proof_1_4
#print axioms P21.Nonsymmetric.pure_critical_glue
#print axioms P21.Nonsymmetric.pure_critical_glue._proof_1_1
#print axioms P21.Nonsymmetric.pure_critical_glue._proof_1_2
#print axioms P21.Nonsymmetric.pure_critical_glue._proof_1_3
#print axioms P21.Nonsymmetric.realized_values_eq
#print axioms P21.Nonsymmetric.realizes_reverse
#print axioms P21.Nonsymmetric.realizes_rotate
#print axioms P21.Nonsymmetric.relabel
#print axioms P21.Nonsymmetric.relabel.eq_1
#print axioms P21.Nonsymmetric.relabelActualRow
#print axioms P21.Nonsymmetric.relabelActualRow._proof_1
#print axioms P21.Nonsymmetric.relabelCritical
#print axioms P21.Nonsymmetric.relabelCritical._proof_1
#print axioms P21.Nonsymmetric.relabelCritical._proof_2
#print axioms P21.Nonsymmetric.relabelCritical._proof_3
#print axioms P21.Nonsymmetric.relabelCritical._proof_4
#print axioms P21.Nonsymmetric.relabelFactorization
#print axioms P21.Nonsymmetric.relabelFactorization._proof_1
#print axioms P21.Nonsymmetric.relabelFourRows
#print axioms P21.Nonsymmetric.relabelSetting
#print axioms P21.Nonsymmetric.relabel_D
#print axioms P21.Nonsymmetric.relabel_Gamma
#print axioms P21.Nonsymmetric.relabel_H
#print axioms P21.Nonsymmetric.relabel_Q
#print axioms P21.Nonsymmetric.relabel_SH
#print axioms P21.Nonsymmetric.relabel_TailPF
#print axioms P21.Nonsymmetric.relabel_W
#print axioms P21.Nonsymmetric.relabel_comp
#print axioms P21.Nonsymmetric.relabel_complement
#print axioms P21.Nonsymmetric.relabel_id
#print axioms P21.Nonsymmetric.relabel_semigroup
#print axioms P21.Nonsymmetric.relabel_singleton_iff
#print axioms P21.Nonsymmetric.relabel_singleton_iff._simp_1_2
#print axioms P21.Nonsymmetric.reverseFullHerzog
#print axioms P21.Nonsymmetric.reverseFullHerzog._proof_1
#print axioms P21.Nonsymmetric.reverseFullHerzog._proof_2
#print axioms P21.Nonsymmetric.reverseFullHerzog.eq_1
#print axioms P21.Nonsymmetric.reverseHerzog
#print axioms P21.Nonsymmetric.reverseHerzog._proof_1
#print axioms P21.Nonsymmetric.reverseHerzog._proof_2
#print axioms P21.Nonsymmetric.reverseHerzog._proof_3
#print axioms P21.Nonsymmetric.reverseHerzog._proof_4
#print axioms P21.Nonsymmetric.reverseHerzog._proof_5
#print axioms P21.Nonsymmetric.reverseHerzog._proof_6
#print axioms P21.Nonsymmetric.reverseHerzog._proof_7
#print axioms P21.Nonsymmetric.reverseHerzog._proof_8
#print axioms P21.Nonsymmetric.reverseHerzog.eq_1
#print axioms P21.Nonsymmetric.reverseHerzog_fA
#print axioms P21.Nonsymmetric.reverseHerzog_fB
#print axioms P21.Nonsymmetric.reversePerm
#print axioms P21.Nonsymmetric.reversePerm._proof_1
#print axioms P21.Nonsymmetric.reversePerm.eq_1
#print axioms P21.Nonsymmetric.reversePerm_next
#print axioms P21.Nonsymmetric.reversePerm_prev
#print axioms P21.Nonsymmetric.reversePerm_self
#print axioms P21.Nonsymmetric.reverse_A_arm_iff
#print axioms P21.Nonsymmetric.reverse_B_arm_iff
#print axioms P21.Nonsymmetric.reverse_isArmA
#print axioms P21.Nonsymmetric.reverse_isArmA._simp_1
#print axioms P21.Nonsymmetric.reverse_isArmB
#print axioms P21.Nonsymmetric.reverse_isArmB._simp_1
#print axioms P21.Nonsymmetric.root_free_level_rigidity
#print axioms P21.Nonsymmetric.rotateFullHerzog
#print axioms P21.Nonsymmetric.rotateFullHerzog._proof_1
#print axioms P21.Nonsymmetric.rotateFullHerzog._proof_2
#print axioms P21.Nonsymmetric.rotateFullHerzog.eq_1
#print axioms P21.Nonsymmetric.rotateHerzog
#print axioms P21.Nonsymmetric.rotateHerzog._proof_1
#print axioms P21.Nonsymmetric.rotateHerzog._proof_2
#print axioms P21.Nonsymmetric.rotateHerzog._proof_3
#print axioms P21.Nonsymmetric.rotateHerzog._proof_4
#print axioms P21.Nonsymmetric.rotateHerzog._proof_5
#print axioms P21.Nonsymmetric.rotateHerzog._proof_6
#print axioms P21.Nonsymmetric.rotateHerzog._proof_7
#print axioms P21.Nonsymmetric.rotateHerzog._proof_8
#print axioms P21.Nonsymmetric.rotateHerzog.eq_1
#print axioms P21.Nonsymmetric.rotateHerzog_fA
#print axioms P21.Nonsymmetric.rotateHerzog_fB
#print axioms P21.Nonsymmetric.rotatePerm
#print axioms P21.Nonsymmetric.rotatePerm.eq_1
#print axioms P21.Nonsymmetric.rotatePerm_one
#print axioms P21.Nonsymmetric.rotatePerm_two
#print axioms P21.Nonsymmetric.rotatePerm_zero
#print axioms P21.Nonsymmetric.rotate_A_arm_iff
#print axioms P21.Nonsymmetric.rotate_B_arm_iff
#print axioms P21.Nonsymmetric.rotate_isArmA
#print axioms P21.Nonsymmetric.rotate_isArmA._simp_1
#print axioms P21.Nonsymmetric.rotate_isArmA_iff
#print axioms P21.Nonsymmetric.rotate_isArmB
#print axioms P21.Nonsymmetric.rotate_isArmB._simp_1
#print axioms P21.Nonsymmetric.rotate_isArmB_iff
#print axioms P21.Nonsymmetric.same_A_arm_unique
#print axioms P21.Nonsymmetric.same_B_arm_unique
#print axioms P21.Nonsymmetric.same_color_complement_cases
#print axioms P21.Nonsymmetric.same_color_complement_cases._proof_1_1
#print axioms P21.Nonsymmetric.same_color_complement_cases._proof_1_2
#print axioms P21.Nonsymmetric.same_color_complement_cases._proof_1_3
#print axioms P21.Nonsymmetric.same_color_complement_cases._proof_1_4
#print axioms P21.Nonsymmetric.same_color_complement_cases._proof_1_5
#print axioms P21.Nonsymmetric.same_color_complement_cases._proof_1_6
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_1
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_10
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_11
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_12
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_13
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_14
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_2
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_3
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_4
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_5
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_6
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_7
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_8
#print axioms P21.Nonsymmetric.same_color_kernel_coefficients._proof_1_9
#print axioms P21.Nonsymmetric.same_color_no_middle_singleton
#print axioms P21.Nonsymmetric.same_color_no_middle_singleton._proof_1_1
#print axioms P21.Nonsymmetric.same_color_no_middle_singleton._proof_1_2
#print axioms P21.Nonsymmetric.same_color_no_middle_singleton._proof_1_3
#print axioms P21.Nonsymmetric.same_color_no_middle_singleton._proof_1_4
#print axioms P21.Nonsymmetric.same_color_no_middle_singleton._proof_1_5
#print axioms P21.Nonsymmetric.same_color_no_middle_singleton._proof_1_6
#print axioms P21.Nonsymmetric.same_color_no_two_endpoint_singletons
#print axioms P21.Nonsymmetric.same_color_no_two_endpoint_singletons._proof_1_1
#print axioms P21.Nonsymmetric.same_color_no_two_endpoint_singletons._proof_1_2
#print axioms P21.Nonsymmetric.same_color_no_two_endpoint_singletons._proof_1_3
#print axioms P21.Nonsymmetric.same_color_no_two_endpoint_singletons._proof_1_4
#print axioms P21.Nonsymmetric.same_color_no_two_endpoint_singletons._proof_1_5
#print axioms P21.Nonsymmetric.same_color_no_two_endpoint_singletons._proof_1_6
#print axioms P21.Nonsymmetric.same_color_no_two_endpoint_singletons._proof_1_7
#print axioms P21.Nonsymmetric.same_color_no_two_endpoint_singletons._proof_1_8
#print axioms P21.Nonsymmetric.select_four_actual_rows
#print axioms P21.Nonsymmetric.selectedValues
#print axioms P21.Nonsymmetric.selectedValues_relabel
#print axioms P21.Nonsymmetric.selected_chain_normalized
#print axioms P21.Nonsymmetric.selected_chain_normalized._proof_1_2
#print axioms P21.Nonsymmetric.selected_chain_normalized._proof_1_3
#print axioms P21.Nonsymmetric.selected_chain_normalized._proof_1_4
#print axioms P21.Nonsymmetric.selected_chain_normalized._proof_1_5
#print axioms P21.Nonsymmetric.selected_chain_normalized._proof_1_6
#print axioms P21.Nonsymmetric.selected_chain_normalized._proof_1_7
#print axioms P21.Nonsymmetric.selected_chain_normalized._proof_1_8
#print axioms P21.Nonsymmetric.selected_chain_normalized._proof_1_9
#print axioms P21.Nonsymmetric.selected_four_Q_card
#print axioms P21.Nonsymmetric.selected_four_terminal_of_colorcap_residuals
#print axioms P21.Nonsymmetric.selected_normalized
#print axioms P21.Nonsymmetric.selected_path_normalized
#print axioms P21.Nonsymmetric.selected_path_normalized._proof_1_2
#print axioms P21.Nonsymmetric.selected_path_normalized._proof_1_3
#print axioms P21.Nonsymmetric.selected_path_normalized._proof_1_4
#print axioms P21.Nonsymmetric.selected_path_normalized._proof_1_5
#print axioms P21.Nonsymmetric.selected_rotated
#print axioms P21.Nonsymmetric.selected_typeII_normalized
#print axioms P21.Nonsymmetric.selected_typeII_normalized._proof_1_2
#print axioms P21.Nonsymmetric.selected_typeII_normalized._proof_1_3
#print axioms P21.Nonsymmetric.selected_typeII_normalized._proof_1_4
#print axioms P21.Nonsymmetric.selected_typeII_normalized._proof_1_5
#print axioms P21.Nonsymmetric.selected_typeII_normalized._proof_1_6
#print axioms P21.Nonsymmetric.selected_typeII_normalized._proof_1_7
#print axioms P21.Nonsymmetric.singleton_W_cap
#print axioms P21.Nonsymmetric.singleton_W_cap._proof_1_1
#print axioms P21.Nonsymmetric.singleton_W_cap_attained
#print axioms P21.Nonsymmetric.singleton_W_cap_attained._proof_1_1
#print axioms P21.Nonsymmetric.singleton_coeff_zero
#print axioms P21.Nonsymmetric.singleton_complement_cap
#print axioms P21.Nonsymmetric.singleton_complement_cap._proof_1_1
#print axioms P21.Nonsymmetric.singleton_critical_bound
#print axioms P21.Nonsymmetric.singleton_critical_bound._proof_1_1
#print axioms P21.Nonsymmetric.singleton_pure_complement
#print axioms P21.Nonsymmetric.singleton_pure_complement._proof_1_1
#print axioms P21.Nonsymmetric.singleton_pure_complement._proof_1_2
#print axioms P21.Nonsymmetric.singleton_saturation
#print axioms P21.Nonsymmetric.singleton_saturation._proof_1_1
#print axioms P21.Nonsymmetric.singleton_saturation._proof_1_10
#print axioms P21.Nonsymmetric.singleton_saturation._proof_1_2
#print axioms P21.Nonsymmetric.singleton_saturation._proof_1_3
#print axioms P21.Nonsymmetric.singleton_saturation._proof_1_4
#print axioms P21.Nonsymmetric.singleton_saturation._proof_1_5
#print axioms P21.Nonsymmetric.singleton_saturation._proof_1_6
#print axioms P21.Nonsymmetric.singleton_saturation._proof_1_7
#print axioms P21.Nonsymmetric.singleton_saturation._proof_1_8
#print axioms P21.Nonsymmetric.singleton_saturation._proof_1_9
#print axioms P21.Nonsymmetric.singleton_saturation_last
#print axioms P21.Nonsymmetric.singletons_same_direction
#print axioms P21.Nonsymmetric.six_arm_atlas
#print axioms P21.Nonsymmetric.six_arm_atlas._proof_1_1
#print axioms P21.Nonsymmetric.six_arm_atlas._proof_1_2
#print axioms P21.Nonsymmetric.support_trichotomy
#print axioms P21.Nonsymmetric.tailPF_of_returns
#print axioms P21.Nonsymmetric.tailPF_of_returns._proof_1_1
#print axioms P21.Nonsymmetric.tailPF_of_returns._proof_1_2
#print axioms P21.Nonsymmetric.tail_bezout_vector
#print axioms P21.Nonsymmetric.tail_bezout_vector._proof_1_1
#print axioms P21.Nonsymmetric.tail_pf_of_generator_returns
#print axioms P21.Nonsymmetric.tail_pf_of_generator_returns._proof_1_1
#print axioms P21.Nonsymmetric.three_singletons_Q_eq_range
#print axioms P21.Nonsymmetric.three_singletons_Q_eq_range._proof_1_1
#print axioms P21.Nonsymmetric.three_singletons_W_unique
#print axioms P21.Nonsymmetric.three_singletons_force_Q_three
#print axioms P21.Nonsymmetric.typeII_exact_input
#print axioms P21.Nonsymmetric.typeII_exact_input._proof_1_10
#print axioms P21.Nonsymmetric.typeII_exact_input._proof_1_3
#print axioms P21.Nonsymmetric.typeII_exact_input._proof_1_4
#print axioms P21.Nonsymmetric.typeII_exact_input._proof_1_5
#print axioms P21.Nonsymmetric.typeII_exact_input._proof_1_6
#print axioms P21.Nonsymmetric.typeII_exact_input._proof_1_7
#print axioms P21.Nonsymmetric.typeII_exact_input._proof_1_8
#print axioms P21.Nonsymmetric.typeII_exact_input._proof_1_9
#print axioms P21.Nonsymmetric.typeII_exact_input.match_1_1
#print axioms P21.Nonsymmetric.unequal_levels_impossible
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_1
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_10
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_11
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_12
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_13
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_14
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_15
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_16
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_17
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_18
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_19
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_2
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_20
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_3
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_4
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_5
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_6
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_7
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_8
#print axioms P21.Nonsymmetric.unequal_levels_impossible._proof_1_9
#print axioms P21.Nonsymmetric.unlabelFactorization
#print axioms P21.Nonsymmetric.unlabelFactorization._proof_1
#print axioms P21.Nonsymmetric.value_cyclic
#print axioms P21.Nonsymmetric.value_perm
#print axioms P21.Nonsymmetric.value_relabel
#print axioms P21.Nonsymmetric.value_relabel_all
#print axioms P21.Nonsymmetric.value_sub_mem
