import P21.Nonsymmetric.ActualClassification
import P21.Nonsymmetric.ActualLabels
import P21.Nonsymmetric.ActualMixed
import P21.Nonsymmetric.Arms
import P21.Nonsymmetric.ColorCap.ActualMinimum
import P21.Nonsymmetric.ColorCap.BoxInput
import P21.Nonsymmetric.ColorCap.BoxPaths
import P21.Nonsymmetric.ColorCap.CompanionBounds
import P21.Nonsymmetric.ColorCap.DPEOneColor
import P21.Nonsymmetric.ColorCap.PositiveMinors
import P21.Nonsymmetric.ColorCap.PrefixArithmetic
import P21.Nonsymmetric.ColorCap.RelativeLattice
import P21.Nonsymmetric.ColorCap.Residuals
import P21.Nonsymmetric.ColorCap.ThreeArms
import P21.Nonsymmetric.ColorCap.WhiteCertificates
import P21.Nonsymmetric.ComplementGeometry
import P21.Nonsymmetric.Corners
import P21.Nonsymmetric.CriticalBox
import P21.Nonsymmetric.Extraction
import P21.Nonsymmetric.FourRowCombinatorics
import P21.Nonsymmetric.Herzog.PseudoFrobenius
import P21.Nonsymmetric.HerzogClassification
import P21.Nonsymmetric.HerzogCoordinates
import P21.Nonsymmetric.HerzogData
import P21.Nonsymmetric.Kernel
import P21.Nonsymmetric.MatchedPair
import P21.Nonsymmetric.MixedColor
import P21.Nonsymmetric.PrimitiveGenerators
import P21.Nonsymmetric.Relabel
import P21.Nonsymmetric.ReturnLevels
import P21.Nonsymmetric.RowAtlas
import P21.Nonsymmetric.Rows
import P21.Nonsymmetric.SameColor
import P21.Nonsymmetric.Saturation
import P21.Nonsymmetric.SelectedExtraction
import P21.Nonsymmetric.Singletons
import P21.Nonsymmetric.ColorCap.MinimumOne.ClassArithmetic
import P21.Nonsymmetric.ColorCap.MinimumOne.ColorA
import P21.Nonsymmetric.ColorCap.MinimumOne.ColorB
import P21.Nonsymmetric.ColorCap.MinimumOne.CyclicInput
import P21.Nonsymmetric.ColorCap.MinimumOne.CyclicReduction
import P21.Nonsymmetric.ColorCap.MinimumOne.EmptyTetrahedron
import P21.Nonsymmetric.ColorCap.MinimumOne.RotationClosure
import P21.Nonsymmetric.ColorCap.MinimumOne.Setup
import P21.Nonsymmetric.ColorCap.MinimumOne.SocleSimplex
import P21.Nonsymmetric.ColorCap.MinimumOneProof
import P21.Nonsymmetric.White.ClassData
import P21.Nonsymmetric.White.ClassReconstruction
import P21.Nonsymmetric.White.CyclicClasses
import P21.Nonsymmetric.White.RelativeIndex
import P21.Nonsymmetric.White.WidthOne
import P21.Nonsymmetric.White.WidthOneBeatty
#check P21.Nonsymmetric.ColorCap.MinimumOne.rowsA
#check P21.Nonsymmetric.ColorCap.MinimumOne.rowsB
#check P21.Nonsymmetric.ColorCap.MinimumOne.inverseClass
#check P21.Nonsymmetric.ColorCap.MinimumOne.inverseClass_identity
#check P21.Nonsymmetric.ColorCap.MinimumOne.class_weight
#check P21.Nonsymmetric.ColorCap.MinimumOne.inverseClass_weight
#check P21.Nonsymmetric.ColorCap.MinimumOne.boundsA_of_actual
#check P21.Nonsymmetric.ColorCap.MinimumOne.inverse_boundsA
#check P21.Nonsymmetric.ColorCap.MinimumOne.colorA_integral_class_contradiction
#check P21.Nonsymmetric.ColorCap.MinimumOne.boundsB_of_actual
#check P21.Nonsymmetric.ColorCap.MinimumOne.class_boundsB
#check P21.Nonsymmetric.ColorCap.MinimumOne.inverse_boundsB
#check P21.Nonsymmetric.ColorCap.MinimumOne.colorB_integral_class_contradiction
#check P21.Nonsymmetric.ColorCap.MinimumOne.exists_cyclic_input
#check P21.Nonsymmetric.ColorCap.MinimumOne.exists_cyclic_age
#check P21.Nonsymmetric.ColorCap.MinimumOne.minimum_one_of_cyclic_white
#check P21.Nonsymmetric.ColorCap.MinimumOne.InSocleSimplex
#check P21.Nonsymmetric.ColorCap.MinimumOne.simplex_positive_or_row
#check P21.Nonsymmetric.ColorCap.MinimumOne.barycentric_weight
#check P21.Nonsymmetric.ColorCap.MinimumOne.minimum_simplex_empty
#check P21.Nonsymmetric.ColorCap.MinimumOne.socle_simplex_empty
#check P21.Nonsymmetric.ColorCap.MinimumOne.rowsA_eq_socleRows
#check P21.Nonsymmetric.ColorCap.MinimumOne.rowsB_eq_socleRows
#check P21.Nonsymmetric.ColorCap.MinimumOne.integral_class_contradiction
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleRows_rotate
#check P21.Nonsymmetric.ColorCap.MinimumOne.rotated_integral_class_contradiction
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleRows
#check P21.Nonsymmetric.ColorCap.MinimumOne.socle
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleMatrix
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleRows_diagonal
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleRows_off_diagonal
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleRows_nonneg
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleRows_weight
#check P21.Nonsymmetric.ColorCap.MinimumOne.socle_minimum_weight
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleMatrix_weight
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleMatrix_det
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleMatrix_det_level
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleMatrix_kernelJ
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleMatrix_kernelK
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleMatrix_span_level
#check P21.Nonsymmetric.ColorCap.MinimumOne.socleMatrix_row_lattice
#check P21.Nonsymmetric.ColorCap.minimum_one_proved
#check P21.Nonsymmetric.ColorCap.three_arms_impossible_of_dpe
#check P21.Nonsymmetric.White.gcd_eq_one_of_nonzero_classes
#check P21.Nonsymmetric.White.exists_positive_inverse
#check P21.Nonsymmetric.White.integral_class_of_unit_coordinate
#check P21.Nonsymmetric.White.combination
#check P21.Nonsymmetric.White.weight_combination
#check P21.Nonsymmetric.White.weight_scale
#check P21.Nonsymmetric.White.classResidues
#check P21.Nonsymmetric.White.classRepresentative
#check P21.Nonsymmetric.White.classRepresentative_equation
#check P21.Nonsymmetric.White.classResidues_sum
#check P21.Nonsymmetric.White.small_mass_impossible
#check P21.Nonsymmetric.White.classResidues_sum_mod
#check P21.Nonsymmetric.White.classResidues_lower
#check P21.Nonsymmetric.White.classResidues_complement
#check P21.Nonsymmetric.White.cyclic_age_of_minimum
#check P21.Nonsymmetric.White.weight_surjective
#check P21.Nonsymmetric.White.relative_coset_iff
#check P21.Nonsymmetric.White.relative_residue_unique
#check P21.Nonsymmetric.White.residue_realized
#check P21.Nonsymmetric.White.relative_level_residue_unique
#check P21.Nonsymmetric.White.relative_level_residue_realized
#check P21.Nonsymmetric.White.relative_level_coset_iff
#check P21.Nonsymmetric.White.relative_cyclic_representatives
#check P21.Nonsymmetric.White.CyclicAge
#check P21.Nonsymmetric.White.CyclicWhiteStatement
#check P21.Nonsymmetric.White.complementary_remainder
#check P21.Nonsymmetric.White.cyclicAge_nonzero
#check P21.Nonsymmetric.White.cyclicAge_sum
#check P21.Nonsymmetric.White.floorJump
#check P21.Nonsymmetric.White.floorJump_bounds
#check P21.Nonsymmetric.White.cyclicAge_jump_sum
#check P21.Nonsymmetric.White.beatty_adjacent_gap
#check P21.Nonsymmetric.White.beatty_gap
#check P21.Nonsymmetric.White.beatty_interleaving_impossible
#check P21.Nonsymmetric.White.floorJump_support
#check P21.Nonsymmetric.White.floorJump_of_support
#check P21.Nonsymmetric.White.NonzeroClasses
#check P21.Nonsymmetric.White.nonzeroClasses_complement
#check P21.Nonsymmetric.White.floorJump_complement
#check P21.Nonsymmetric.White.beatty_div_antitone
#check P21.Nonsymmetric.White.beatty_index_lt
#check P21.Nonsymmetric.White.beatty_last
#check P21.Nonsymmetric.White.beatty_partition_impossible
#check P21.Nonsymmetric.White.cyclicWhite_sorted_impossible
#check P21.Nonsymmetric.White.cyclic_white_proved
#check P21.Nonsymmetric.ColorCap.minimum_one_proved
#check P21.Nonsymmetric.ColorCap.three_arms_impossible_of_dpe
#check P21.Nonsymmetric.White.cyclic_white_proved
example : P21.Nonsymmetric.ColorCap.MinimumOneStatement := P21.Nonsymmetric.ColorCap.minimum_one_proved
#print P21.Nonsymmetric.ColorCap.MinimumOneStatement
#print P21.Nonsymmetric.ColorCap.BoxPositiveExitStatement
