import P21.Nonsymmetric.ColorCap.DPE.Canonical
import P21.Nonsymmetric.ColorCap.DPE.ChronologicalPrefix
import P21.Nonsymmetric.ColorCap.DPE.Exhaustion
import P21.Nonsymmetric.ColorCap.DPE.FirstThirdColor
import P21.Nonsymmetric.ColorCap.DPE.PathShape
import P21.Nonsymmetric.ColorCap.DPE.ReciprocalRank
import P21.Nonsymmetric.ColorCap.DPE.Rotation
import P21.Nonsymmetric.ColorCap.DPE.SuccessfulPrefix
import P21.Nonsymmetric.ColorCap.DPE.TerminalCoordinates
import P21.Nonsymmetric.ColorCap.DPE.Trace
import P21.Nonsymmetric.ColorCap.DPE.TraceSuccessfulPrefix
import P21.Nonsymmetric.ColorCap.DPE.TwoColor12
import P21.Nonsymmetric.ColorCap.DPE.TwoColor13
import P21.Nonsymmetric.ColorCap.FullColorCap

#check P21.Nonsymmetric.ColorCap.FiringTrace.head_zero
#check P21.Nonsymmetric.ColorCap.one_color_trace_sink_impossible
#check P21.Nonsymmetric.ColorCap.ProperNonzeroPredecessors
#check P21.Nonsymmetric.ColorCap.ProperNonzeroPredecessors.prefix
#check P21.Nonsymmetric.ColorCap.ProperNonzeroPredecessors.count_le_zero
#check P21.Nonsymmetric.ColorCap.ProperNonzeroPredecessors.count_lt_zero_of_last_zero
#check P21.Nonsymmetric.ColorCap.CrossingWitness
#check P21.Nonsymmetric.ColorCap.CrossingWitness.at_last
#check P21.Nonsymmetric.ColorCap.nth_occurrence_split
#check P21.Nonsymmetric.ColorCap.occurrence_source_ends_zero
#check P21.Nonsymmetric.ColorCap.count_eq_zero_of_members
#check P21.Nonsymmetric.ColorCap.prefix_at_zero_count
#check P21.Nonsymmetric.ColorCap.shifted_prefix_actual
#check P21.Nonsymmetric.ColorCap.prefix_continues_zero
#check P21.Nonsymmetric.ColorCap.canonical_trace_sink_impossible
#check P21.Nonsymmetric.ColorCap.box_positive_exit_proved
#check P21.Nonsymmetric.ColorCap.first_nonzero_occurrence_actual
#check P21.Nonsymmetric.ColorCap.first_row2_after_01_actual
#check P21.Nonsymmetric.ColorCap.first_row1_after_02_actual
#check P21.Nonsymmetric.ColorCap.first_third_12_to_3_certificate
#check P21.Nonsymmetric.ColorCap.first_third_13_to_2_certificate
#check P21.Nonsymmetric.ColorCap.first_third_12_rank
#check P21.Nonsymmetric.ColorCap.first_third_12_to_3_actual_impossible
#check P21.Nonsymmetric.ColorCap.first_third_13_rank
#check P21.Nonsymmetric.ColorCap.first_third_13_to_2_actual_impossible
#check P21.Nonsymmetric.ColorCap.first_nonzero_color_order
#check P21.Nonsymmetric.ColorCap.first_third_color_actual_impossible
#check P21.Nonsymmetric.ColorCap.FiringTrace.endpoint_inBox
#check P21.Nonsymmetric.ColorCap.FiringTrace.nonzero_followed_by_zero
#check P21.Nonsymmetric.ColorCap.FiringTrace.properNonzeroPredecessors
#check P21.Nonsymmetric.ColorCap.continued_zero_shift_bound
#check P21.Nonsymmetric.ColorCap.actual_shifted_before_crossing
#check P21.Nonsymmetric.ColorCap.actual_shifted_terminal
#check P21.Nonsymmetric.ColorCap.reciprocal_residue_actual
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.dual_prefix_of_actuality
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.reciprocal_separator
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.dual_rank
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.dual_next_residue_rank
#check P21.Nonsymmetric.ColorCap.permutePoint
#check P21.Nonsymmetric.ColorCap.BoxInput.rotate
#check P21.Nonsymmetric.ColorCap.BoxInput.rotate_rows
#check P21.Nonsymmetric.ColorCap.BoxInput.start_of_row0
#check P21.Nonsymmetric.ColorCap.permutePoint_fire
#check P21.Nonsymmetric.ColorCap.inBox_permute_iff
#check P21.Nonsymmetric.ColorCap.BoxPath.rotateGeneral
#check P21.Nonsymmetric.ColorCap.BoxPath.rotate
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.E
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.U
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.separator
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.coordinate_injective
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.coordinateU_injective
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.E_slot_count
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.U_slot_count
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.cover_by_next_residue
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.last_rank
#check P21.Nonsymmetric.ColorCap.SuccessfulPrefix.terminal_rank
#check P21.Nonsymmetric.ColorCap.terminal12Point
#check P21.Nonsymmetric.ColorCap.terminal13Point
#check P21.Nonsymmetric.ColorCap.trace_terminal12
#check P21.Nonsymmetric.ColorCap.trace_terminal13
#check P21.Nonsymmetric.ColorCap.terminal12Point_coordinates
#check P21.Nonsymmetric.ColorCap.terminal13Point_coordinates
#check P21.Nonsymmetric.ColorCap.execute
#check P21.Nonsymmetric.ColorCap.execute_append
#check P21.Nonsymmetric.ColorCap.FiringTrace
#check P21.Nonsymmetric.ColorCap.BoxPath.exists_trace
#check P21.Nonsymmetric.ColorCap.FiringTrace.execute_eq
#check P21.Nonsymmetric.ColorCap.FiringTrace.toBoxPath
#check P21.Nonsymmetric.ColorCap.FiringTrace.prefix_trace
#check P21.Nonsymmetric.ColorCap.FiringTrace.prefix_path
#check P21.Nonsymmetric.ColorCap.FiringTrace.endpoint_eq_sub_sum
#check P21.Nonsymmetric.ColorCap.trace_successfulPrefix12
#check P21.Nonsymmetric.ColorCap.trace_successfulPrefix12_actual
#check P21.Nonsymmetric.ColorCap.trace_successfulPrefix13
#check P21.Nonsymmetric.ColorCap.trace_successfulPrefix13_actual
#check P21.Nonsymmetric.ColorCap.X12
#check P21.Nonsymmetric.ColorCap.Y12
#check P21.Nonsymmetric.ColorCap.terminal12_count_bounds
#check P21.Nonsymmetric.ColorCap.terminal12_not_sinkA
#check P21.Nonsymmetric.ColorCap.terminal12_sinkD_impossible
#check P21.Nonsymmetric.ColorCap.terminal12_last_row1_impossible
#check P21.Nonsymmetric.ColorCap.terminal12_last_row1_of_prefix
#check P21.Nonsymmetric.ColorCap.terminal12_sinkB_nonnegativeX_impossible
#check P21.Nonsymmetric.ColorCap.terminal12_sinkB_negativeX_certificate
#check P21.Nonsymmetric.ColorCap.terminal12_sinkC_certificate
#check P21.Nonsymmetric.ColorCap.terminal12_sinkC_ELR_bound
#check P21.Nonsymmetric.ColorCap.terminal12_sinkC_ELR_extended
#check P21.Nonsymmetric.ColorCap.terminal12_negativeD_predecessor_bound
#check P21.Nonsymmetric.ColorCap.terminal12_nonnegativeD_count_bound
#check P21.Nonsymmetric.ColorCap.terminal12_reciprocal_rank
#check P21.Nonsymmetric.ColorCap.two_color12_trace_sink_impossible
#check P21.Nonsymmetric.ColorCap.X13
#check P21.Nonsymmetric.ColorCap.Y13
#check P21.Nonsymmetric.ColorCap.terminal13_count_bounds
#check P21.Nonsymmetric.ColorCap.terminal13_not_sinkB
#check P21.Nonsymmetric.ColorCap.terminal13_sinkD_impossible
#check P21.Nonsymmetric.ColorCap.terminal13_last_row2_of_prefix
#check P21.Nonsymmetric.ColorCap.terminal13_sinkA_certificate
#check P21.Nonsymmetric.ColorCap.terminal13_sinkC_certificate
#check P21.Nonsymmetric.ColorCap.terminal13_sinkC_ELR_bound
#check P21.Nonsymmetric.ColorCap.terminal13_reciprocal_rank
#check P21.Nonsymmetric.ColorCap.two_color13_trace_sink_impossible
#check P21.Nonsymmetric.ColorCap.three_arms_impossible
#check P21.Nonsymmetric.actual_three_A_excluded_residual_free
#check P21.Nonsymmetric.actual_three_B_excluded_residual_free
#check P21.Nonsymmetric.actual_labels_compatible_residual_free
#check P21.Nonsymmetric.actual_labels_terminal_residual_free
#check P21.Nonsymmetric.selected_four_terminal
#check P21.Nonsymmetric.nonsymmetric_selected_four
#check P21.Nonsymmetric.nonsymmetric_Q_ge_four
#print P21.Nonsymmetric.ColorCap.BoxPositiveExitStatement
