import P21.Nonsymmetric.ColorCap.DPE.TwoColor13

open P21.Nonsymmetric.ColorCap

#check terminal13_not_sinkB
#check terminal13_count_bounds
#check terminal13_sinkD_impossible
#check terminal13_last_row2_of_prefix
#check terminal13_sinkA_certificate
#check terminal13_reciprocal_rank
#check terminal13_sinkC_certificate
#check terminal13_sinkC_ELR_bound
#check two_color13_trace_sink_impossible
