import P21.External.SymmetricThreeGeneratorProof
import P21.Symmetric.Classification.AperyCardinality
import P21.Symmetric.Classification.CriticalRelations
import P21.Symmetric.Classification.GcdDecomposition
import P21.Symmetric.Classification.GlueExistence
import P21.Symmetric.Classification.SymmetricRigidity
import P21.Symmetric.Classification.TailNumericalSemigroup
import P21.Symmetric.Classification.TopFactorization
import P21.Symmetric.Classification.UniqueTop
import P21.Symmetric.FullClosure
import P21.External.SymmetricThreeGenerator
import P21.Symmetric.Closure
#check P21.Symmetric.symmetric_three_generator_gluing
#check P21.Symmetric.Classification.tail_apery_lower
#check P21.Symmetric.Classification.tail_apery_le_of_emod
#check P21.Symmetric.Classification.tail_apery_emod_le
#check P21.Symmetric.Classification.tail_apery_emod_injective
#check P21.Symmetric.Classification.tail_apery_emod_surjective
#check P21.Symmetric.Classification.tail_apery_card
#check P21.Symmetric.Classification.tail_apery_reduce
#check P21.Symmetric.Classification.tail_apery_rectangle_card
#check P21.Symmetric.Classification.CriticalRelation
#check P21.Symmetric.Classification.criticalRelation_exists
#check P21.Symmetric.Classification.CriticalRelation.ge_two
#check P21.Symmetric.Classification.CriticalRelation.coeff_unique
#check P21.Symmetric.Classification.CriticalRelation.not_offDirection
#check P21.Symmetric.Classification.CriticalRelation.below_unique
#check P21.Symmetric.Classification.tail_not_two
#check P21.Symmetric.Classification.decomposition_glue_data
#check P21.Symmetric.Classification.special_pair_glue_data
#check P21.Symmetric.Classification.primitive_pair_data
#check P21.Symmetric.Classification.rectangle_glue_data
#check P21.Symmetric.Classification.glue_exists_of_symmetric
#check P21.Symmetric.Classification.nonneg_mul_mem
#check P21.Symmetric.Classification.primitive_mem_of_lcm_gap
#check P21.Symmetric.Classification.boundary_determinant_dvd
#check P21.Symmetric.Classification.rectangular_boundary_zero
#check P21.Symmetric.Classification.rectangular_zero_boundary_decomposition
#check P21.Symmetric.Classification.unique_top_apery_rectangle
#check P21.Symmetric.Classification.unique_top_rectangle_injective
#check P21.Symmetric.Classification.rectangular_boundary_relation
#check P21.Symmetric.Classification.tail_generator_pos
#check P21.Symmetric.Classification.tail_nonneg
#check P21.Symmetric.Classification.tail_minimal
#check P21.Symmetric.Classification.tail_cofinite
#check P21.Symmetric.Classification.tailSemigroup
#check P21.Symmetric.Classification.tail_common_divisor_dvd_one
#check P21.Symmetric.Classification.tail_gcd_eq_one
#check P21.Symmetric.Classification.value_permuted_three
#check P21.Symmetric.Classification.tail_bezout
#check P21.Symmetric.Classification.symmetric_frobenius
#check P21.Symmetric.Classification.TailApery
#check P21.Symmetric.Classification.symmetry_apery_top
#check P21.Symmetric.Classification.symmetry_apery_complement
#check P21.Symmetric.Classification.symmetry_apery_complement_iff
#check P21.Symmetric.Classification.symmetry_apery_le_top
#check P21.Symmetric.Classification.apery_actual_zero
#check P21.Symmetric.Classification.apery_gap_of_sub_mem
#check P21.Symmetric.Classification.two_representations_sub_lcm_mem
#check P21.Symmetric.Classification.two_representations_lcm_apery
#check P21.Symmetric.Classification.primitive_mem_of_two_representations
#check P21.Symmetric.Classification.two_top_representations_glue_data
#check P21.Symmetric.Classification.tail_apery_pair_rep
#check P21.Symmetric.Classification.tail_apery_reduction
#check P21.Symmetric.Classification.unique_top_rectangle
#check P21.Symmetric.Classification.unique_top_boundary_relations
#check P21.Symmetric.Classification.unique_top_glue_data
#check P21.Symmetric.symmetric_tail_type_le_four
#print P21.Symmetric.SymmetricTail
#print P21.Symmetric.SymmetricGlueData
#print P21.Symmetric.SymmetricThreeGeneratorGluingStatement
#print P21.Symmetric.symmetric_tail_from_glue_data
example : P21.Symmetric.SymmetricThreeGeneratorGluingStatement :=
  P21.Symmetric.symmetric_three_generator_gluing
example (g : P21.Generators) (s : g.Setting) (F : ℤ)
    (hF : s.semigroup.IsFrobenius F) (hcan : s.semigroup.Canonical F g.m)
    (hsym : P21.Symmetric.SymmetricTail g) : s.semigroup.type ≤ 4 :=
  P21.Symmetric.symmetric_tail_type_le_four g s F hF hcan hsym

